project:
  type: website
 

website:
  page-navigation: true
  title: "Wirkungsgrad auf dem Radergometer im Sitzen und Stehen"
  #navbar:
    #left:
      #- about.qmd
      #- href: Wirkungsgrad.qmd
      #  text: Wirkungsgrad
      #- Wirkungsgrad.qmd
      #- Spiro-Messwerte.qmd
      #- EPOC-Daten.qmd
      #- Ergometer-Daten.qmd
      #- Laktat.qmd
      #- Datensätze.qmd
      
  page-footer:
    right: "[Quarto](https://quarto.org/)"
    left: "Johannes Will, 2024"
      
  sidebar:
    logo: "images/Logo_η_3.png"
    pinned: false
    align: center
   

    style: "docked"
    search: true
    collapse-level: 3
    contents:
      - about.qmd
      - Wirkungsgrad.qmd
      - Spiro-Messwerte.qmd
      #- EPOC-Daten.qmd
      - section: EPOC/index_EPOC.qmd
        contents: 
          - EPOC/Proband01.qmd
          - EPOC/Proband06.qmd
          - EPOC/Proband10.qmd 
          - EPOC/Proband13.qmd
          - EPOC/Proband15.qmd 
          - EPOC/Proband19.qmd
          - EPOC/Proband20.qmd 
          - EPOC/Proband22.qmd
          - EPOC/Proband23.qmd 
      - Laktat.qmd
      - section: Ergometer/index_Ergometer.qmd
        contents: 
          - Ergometer/Efficiency.qmd
          - Ergometer/Innere_Arbeit.qmd
          - Ergometer/Pedal_Smoothness.qmd 
      - Datensätze.qmd
      #- Test.qmd

format:
  html: 
    grid:
      sidebar-width: 300px
      body-width: 1600px
      margin-width: 250px
      gutter-width: 1.5rem
      
    theme:
      light: [cosmo, theme.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true
    toc-expand: 3
    toc-title: Inhalt auf dieser Seite
    toc-location: right 

    
    smooth-scroll: true
    
    code-fold: true
    code-tools: true
    code-copy: true
    code-overflow: wrap
    
    lightbox: true
    



