project:
  type: website

website:
  title: "Wirkungsgrad-Rad"
  navbar:
    left:
      - href: index.qmd
        text: Informationen Studie
      - Wirkungsgrad.qmd

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true



