project:
  type: website
 

website:
  title: "Wirkungsgrad-Rad"
  navbar:
    left:
      - href: index.qmd
        text: Informationen Studie
      - Wirkungsgrad.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-expand: 3
    toc-title: Inhalt
    toc-location: left 

    
    smooth-scroll: true
    
    code-fold: true
    code-tools: true
    code-copy: true
    
    lightbox: true
    



