project:
  title: "Wirkungsgrad-Rad.github.io"
  type: website
  output-dir: _site
  resources: 
  - shinylive-sw.js
  
execute:
  engine: knitr
 
website:
  title: "Wirkungsgrad auf dem Radergometer im Sitzen und Stehen"
  page-navigation: true

  page-footer:
    right: "[Quarto](https://quarto.org/)"
    left: "Johannes Will, 2024"
      
  sidebar:
    logo: "images/Logo_Î·_3.png"
    pinned: false
    align: center
    style: "docked"
    search: true
    collapse-level: 3 #Ab welchem Level die Unterpunkt nicht mehr angezeigt werden. Bei 2 wird bspw. bei Energieumsatz die Unterpunkte eingeklappt
    contents:
       - section: Theoretischer_Hintergrund/index_Theoretischer_Hintergrund.qmd
         contents: 
           - Theoretischer_Hintergrund/Wirkungsgrad_Theorie.qmd
           - section: Theoretischer_Hintergrund/Energieumsatzberechnung/index_Energieumsatzberechnung.qmd
             contents:
              - Theoretischer_Hintergrund/Energieumsatzberechnung/Aerobe_Energiebereitstellung.qmd
              - Theoretischer_Hintergrund/Energieumsatzberechnung/Anaerobe_laktazide_Energiebereitstellung.qmd
              - Theoretischer_Hintergrund/Energieumsatzberechnung/Anaerobe_alaktazide_Energiebereitstellung.qmd
           - Theoretischer_Hintergrund/Mechanische_Arbeit.qmd
           - Theoretischer_Hintergrund/Innere_Arbeit.qmd
           - Theoretischer_Hintergrund/Sitzen_Stehen.qmd
       - Forschungsfragen_Hypothesen.qmd
       - section: Methodik/index_Methodik.qmd
         contents: 
           - Methodik/Stichprobe.qmd
           - Methodik/Messmethoden.qmd
           - Methodik/Studiendesign.qmd
           - Methodik/Statistische_Analyseverfahren
       - section: Ergebnisse/index_Ergebnisse.qmd
         contents:
           - Ergebnisse/Drehzahl_Stufentests.qmd
           - Ergebnisse/VO2_Daten.qmd
           - Ergebnisse/EPOC_Daten.qmd
           - Ergebnisse/Ergometer_Daten.qmd
           - Ergebnisse/Wirkungsgrad_Statistik.qmd
       - Abkuerzungsverzeichnis.qmd
       - Quellen.qmd
      

lang: de
number-sections: true
bibliography: references.bib
csl: apa.csl
format:
  html: 
    grid:
      sidebar-width: 250px
      body-width: 1050px
      margin-width: 200px
      gutter-width: 1.5rem
      
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss] # from https://github.com/sta210-s22/website/blob/main/_quarto.yml
    css: styles.css
    toc: true
    toc-expand: 3
    toc-title: Inhalt auf dieser Seite
    toc-location: right 

    
    #smooth-scroll: true
    
    code-fold: true
    code-tools: true
    code-copy: true
    code-overflow: wrap
    
    lightbox: true
    



