---
title: "Diskussion"

execute:
  message: false
  engine: knitr
  echo: false
  warning: false
  error: false
  
bibliography: references.bib
lang: de
number-sections: false
editor: 
  markdown: 
    wrap: 72

tbl-cap-location: bottom
---

```{css}
#| echo: false
p {
  text-align: justify
}
caption, .figure-caption {
  text-align: left;
}
figure.quarto-float-tbl figcaption {
  text-align: left !important;
}
figure figcaption {
  text-align: justify;
}
```

Die vorliegende Untersuchung prüfte erstmals systematisch die Unterschiede des muskulären Wirkungsgrads (η~muskulär~) zwischen sitzender und stehender Fahrposition bei verschiedenen Belastungsintensitäten. Der η~muskulär~ beschreibt dabei das Verhältnis zwischen der über den Belastungszeitraum summierten inneren und externen Arbeit zur Summe der aeroben und anaeroben metabolischen Arbeit abzüglich der Arbeit des Ruheumsatzes (@tbl-Wirkungsgrad_Berechnungen). Die Ergebnisse bestätigen die erwartete Intensitätsabhängigkeit der Unterschiede zwischen den Fahrpositionen.

::: {.callout-note collapse="true"}
#### Berechnungswege verschiedener Wirkungsgrade

| Wirkungsgrade |                   Berechnung                   |
|---------------|:----------------------------------------------:|
| η~Brutto~     |               W~mech~ / W~Aerob~               |
| η~Netto~      |         W~mech~ / (W~Aerob~ - W~Ruhe~)         |
| η~Total~      |          W~mech~ / (W~Tot~ - W~Ruhe~)          |
| η~muskulär~   |    (W~mech~ + W~Int~) / (W~Tot~ - W~Ruhe~)     |
| η~Arbeit~     | W~mech~ / (W~Tot~ - W~Ruhe~ - W~Leerbewegung~) |
| η~delta~      |               ΔW~mech~ / ΔW~Tot~               |

: Modifizierte Berechnungswege der Wirkungsgrade nach Gaesser und Brooks (1975), Winter (1979), Luhtanen et al. (1987) und Böning et al. (2017), ergänzt um den Gesamtwirkungsgrad (η~Total~). {#tbl-Wirkungsgrad_Berechnungen tbl-colwidths="\[30,70\]" .hover }
:::

## Betrachtung und Einordnung der Hauptergebnisse des η~muskulär~ 

Basierend auf der Hypothese, dass sich die Unterschiede des muskulären Wirkungsgrades zwischen den Fahrpositionen intensitätsabhängig verhalten, wurde eine zweifaktorielle Varianzanalyse mit Messwiederholung durchgeführt. Diese zeigte einen signifikanten Interaktionseffekt zwischen Intensität und Bedingung. Die anschließenden Post-hoc-Analysen mittels gepaarter t-Tests mit Bonferroni-Korrektur zeigten bei leichter Intensität signifikante Unterschiede zwischen den Positionen (p = .011) mit einer großen Effektstärke (d = 1.36). Der muskuläre Wirkungsgrad in sitzender Position (25.68%) war signifikant höher als der η~muskulär~ in stehender Position (24.20%). Bei moderater Intensität konnten keine signifikanten Unterschiede zwischen den Positionen festgestellt werden, es zeigte sich jedoch eine mittlere Effektstärke (p = .153, d = .76). Auch im Vergleich der moderaten Intensitätsstufe war der η~muskulär~ im Sitzen (24.92%) höher als im Stehen (24.08%). Bei schwerer Intensität näherten sich die Werte weiter an, was sich in einem nicht-signifikanten Unterschied (p = .807) und einer kleinen Effektstärke (d = .40) widerspiegelte, mit weiterhin leicht höheren Werten im Sitzen (24.36%) als im Stehen (23.92%).

Somit ließen sich die erwarteten Annahmen bestätigen, dass sich ein intensitätsbezogenes Verhalten des muskulären Wirkungsgrades im Stehen und Sitzen zeigte. Diese Annahmen basieren auf früheren Forschungsergebnissen, die bei niedrigen bis moderaten Intensitäten in stehender Position konsistent reduzierte Wirkungsgrade sowie erhöhte physiologische Belastungsparameter dokumentierten [@Ryschon1991a; @Tanaka1996a; @Berkemeier2020], wobei die untersuchten Parameter mit zunehmender Belastungsintensität eine systematische Angleichung der positionsspezifischen Unterschiede aufwiesen, insbesondere oberhalb von etwa 80% der $\dot{V}O_{2,max}$ [@Arkesteijn2016; @Harnish2007; @Millet2002; @Hansen2008; @Tanaka1996a]. 
Diese Nivellierung spiegelte sich in der vorliegenden Studie in den sukzessiv abnehmenden Differenzen der berechneten η~muskulär~-Werte zwischen den Positionen bei moderater und schwerer Intensität wider. Während zwischen den leichten Intensitäten im Sitzen und Stehen noch ein signifikanter Unterschied bestand, nahmen die Differenzen mit steigender Belastungsintensität stetig ab und zeigten keine signifikanten Differenzen mehr zwischen den moderaten und schweren Intensitätsstufen. Bei der moderaten Intensitätsstufe in dieser Untersuchung lag das errechnete Fließgleichgewicht des Sauerstoffvolumenstroms im Sitzen im Mittel bei 80.0% der $\dot{V}O_{2,max}$ des Stufentests und im Stehen bei 80.5%. Diese Intensitäten fallen somit die Grenze des Bereichs, ab dem in der Literatur in den meisten Untersuchungen eine Angleichung der physiologischen Reaktionen auf eine Belastung in sitzender und stehender Position zu beobachten war.<br>
Ein in der Literatur genannter Erklärungsansatz für die intensitätsabhängigen Unterschiede ist die notwendige aktive Stabilisierung des Körperschwerpunkts im Stehen, während dieser in sitzender Position passiv durch den Sattel unterstützt wird. Dabei ermöglichen die biomechanischen Charakteristika der stehenden Position, wie der Einsatz der koordinierten Armarbeit beim Fahren aus dem Sattel und die anterior verlagerte Hüftposition, möglicherweise eine effektivere Kraftübertragung und optimierte Nutzung des Körpergewichts, könnten jedoch bei submaximalen Intensitäten zu erhöhtem metabolischen Aufwand führen. Diese biomechanischen Eigenschaften scheinen allerdings bei intensiven Belastungen vorteilhaft sein, wie frühere Studien durch eine höhere mögliche Leistungsabgabe in stehender Position bei kurzen und intensiven Belastungen dokumentierten [@Hansen2008; @Millet2002].

Die Analyse der Einzelkomponenten des η~muskulär~, bestehend aus externer mechanischer Arbeit (W~mech~), innerer Arbeit (W~Int~) und absolvierter Gesamtarbeit aus allen Stoffwechselwegen (W~TOT~), offenbart ein differenzierteres Bild. Während sich W~TOT~ nicht signifikant zwischen den Bedingungen unterscheidet, ist ein hochsignifikanter Unterschied in der Summe von W~mech~ und W~Int~ zwischen den Bedingungen nachweisbar. Die detaillierte Analyse offenbart dabei eine signifikant höhere W~mech~ im Stehen, während W~Int~ im Sitzen signifikant höhere Werte aufweist. Die deutlich größeren W~Int~-Werte im Sitzen resultieren dabei in dem signifikanten Unterschied der Summe von W~mech~ und W~Int~, welche die Berechnungsgrundlage für η~muskulär~ darstellt.<br>
Die initial getroffene Annahme, dass die vermuteten Unterschiede von η~muskulär~ primär auf Differenzen in der absolvierten metabolischen Arbeit bei vergleichbarer W~mech~ und W~Int~ zurückzuführen sein würden, konnte nicht bestätigt werden, da die vorliegende Untersuchung keine signifikanten Unterschiede bezüglich der verschiedenen Gesamtenergieumsatzkomponenten nachweisen konnte. Die identifizierten signifikanten Unterschiede lassen sich daher höchstwahrscheinlich auf die signifikant höhere W~Int~-Werte im Sitzen zurückführen. Um diese Annahme zu überprüfen, wurde η~total~ bestimmt, welcher analog zu η~muskulär~, jedoch unter Ausschluss der inneren Arbeit, berechnet wurde. Im Gegensatz zu η~muskulär~ zeigt η~total~ weder einen signifikanten Interaktionseffekt zwischen Intensität und Bedingung noch signifikante Unterschiede im paarweisen Vergleich zwischen den Bedingungen. Dies bestätigt die Annahme, dass die signifikant höhere berechnete innere Arbeit im Sitzen für die signifikanten Unterschiede des η~muskulär~ in der leichten Intensität verantwortlich ist.

Die detaillierte Analyse der berechneten inneren Arbeit bzw. inneren Leistung zeigt eine kubische Abhängigkeit der hier berechneten inneren Leistung (P~Int,Kinematik,Modell~) von der Drehzahl. P~Int,Kinematik,Modell~, welche aus der Kombination von Modellsimulationen und tatsächlichen 3D-Kinematik-Daten erstellt wurde, zeigt bei gleichen Drehzahlen vergleichbar hohe Werte der inneren Arbeit in beiden Positionen. Allerdings unterscheiden sich die mittleren Drehzahlen signifikant zwischen Sitzen, mit 89 U·min^-1^, und Stehen, mit 69,8 U·min^-1^, und bleiben über die Intensitätsstufen konstant. Dies resultiert in einer signifikant höheren P~Int,Kinematik,Modell~ im Sitzen im Vergleich zum Stehen bei den von den Probanden selbst selektierten Drehzahlen.<br>
Basierend auf den nicht signifikanten Unterschieden des η~total~ und des physiologischen Gesamtenergieumsatzes erscheint die Annahme plausibel, dass eigentlich auch die Summe aus innerer und externer Arbeit für beide Bedingungen troz der unterschiedlichen Dreahzahlen vergleichbar sein sollte. Diese Annahme wird durch die berechneten Netto- und Bruttowirkungsgrade gestützt. Diese Wirkungsgradberechnungen basieren ausschließlich auf dem aeroben Energieumsatz (Nettowirkungsgrad exklusive Ruheumsatz, Bruttowirkungsgrad inklusive Ruheumsatz) sowie der absolvierten externen mechanischen Leistung. Beide Wirkungsgrade zeigen zwar einen signifikanten Interaktionseffekt von Bedingung und Intensität, jedoch keine signifikanten Unterschiede in den Post-hoc-Tests beim Vergleich der jeweiligen Belastungsintensitäten zwischen den Bedingungen, was auf eine vergleichbare metabolische Auslastung bei der absolvierten mechanischen Arbeit in beiden Bedingungen hinweist.

Da die berechneten P~Int,Kinematik,Modell~-Werte für das Sitzen mit den berechneten P~Int~-Werten aus der Literatur vergleichbar sind [@Hansen2004], jedoch keine Referenzwerte der inneren Leistung für das Fahren im Stehen existieren, wird angenommen, dass die Berechnungsmethode der inneren Leistung für das Fahren im Stehen möglicherweise keine validen Ergebnisse liefert und einer methodischen Überarbeitung bedarf. Die Möglichkeiten dieser Überarbeitung werden im Kapitel Ausblick diskutiert.<br>
Für einen validen direkten Vergleich der in dieser Studie erhobenen Wirkungsgrade zwischen sitzender und stehender Position ist somit eher der Brutto-, Netto- oder Gesamtwirkungsgrad zu empfehlen, da in diesen Wirkungsgradberechnungen die innere Arbeit nicht mit einbezogen wird.<br>
Bei der Betrachtung der ermittelten Werte des muskulären Wirkungsgrads im Literaturvergleich fällt auf, dass die berechneten Werte des η~muskulär~ mit durchschnittlich 24,53% (Range: 22,46 - 26,91%) deutlich unterhalb der von @Bell2009 berichteten durchschnittlichen η~muskulär~-Werte von 31,0% liegen. Diese Diskrepanz erscheint nachvollziehbar, da die Ergebnisse von @Bell2009 auch im Vergleich zur übrigen Literatur außergewöhnlich hohe Wirkungsgrade aufweisen, was bereits in der Originalpublikation kritisch reflektiert wurde. Eine direkte Vergleichbarkeit der Absolutwerte mit @Bell2009 ist daher nur eingeschränkt möglich. Die in der vorliegenden Studie ermittelten η~muskulär~-Werte liegen zudem leicht unterhalb der von @Luhtanen1987 berichteten Durchschnittswerte von ca. 25,35% (Range: 21,0% - 29,7%).


## Einordnung und Diskussion der weiteren Wirkungsgradberechnungen

Ergänzend zur Hypothesentestung des muskulären Wirkungsgrades wurden zur Identifikation und Charakterisierung potenzieller Wirkmechanismen weitere komparative statistische Analysen der berechneten Wirkungsgrade durchgeführt.
Die Analysen offenbarten, wie bereits dargestellt, ausschließlich beim Netto- und Bruttowirkungsgrad einen signifikanten Interaktionseffekt zwischen Position und Intensität. Die Post-hoc-Tests konnten jedoch beim Vergleich der Intensitätsstufen zwischen der sitzenden und stehenden Position bei beiden Wirkungsgraden keine signifikanten Unterschiede nachweisen. Die weiteren statistischen und deskriptiven Analysen der Wirkungsgradberechnungen werden, im Folgenden diskutiert.

Der η~Brutto~ zeigte bezogen auf die Intensität signifikante Unterschiede. Die Post-hoc-Analysen zeigten zwischen leichter und schwerer Intensität eine statistisch signifikante Differenz. Diese Beobachtung entsprach den theoretischen Erwartungen, da der Bruttowirkungsgrad eine charakteristische Intensitätsabhängigkeit aufweist. Der zugrundeliegende Mechanismus basiert darauf, dass der in die Berechnung einbezogene Ruheumsatz bei steigendem Energieumsatz einen proportional abnehmenden Anteil darstellt, wodurch der η~Brutto~ systematisch mit zunehmender Intensität ansteigt. Diese systematische Steigerung korrespondierte mit den Befunden mehrerer Studien [@Seabury1977; @Chavarren1999; @Zoladz2023a; @Boning2017], die analog eine positive Korrelation zwischen Belastungsintensität und η~Brutto~ dokumentierten. Die ermittelten η~Brutto~-Werte lagen mit einer Spanne von 19.65-25.76% und einem arithmetischen Mittel von 22.43% im oberen Bereich der in @tbl-Wirkungsgrad am häufigsten dokumentierten η~Brutto~-Werte von etwa 19-23%.

Der Nettowirkungsgrad eliminiert durch den Ausschluss des Ruheenergieumsatzes dessen Einfluss auf die Berechnung und zeigt folglich systematisch höhere Werte als der η~Brutto~. Die hier ermittelten η~Netto~-Werte lagen mit einer Spanne von 22.13-28.18% und einem arithmetischen Mittel von 24.94% oberhalb der in @tbl-Wirkungsgrad am häufigsten dokumentierten η~Netto~-Werte von ca. 19-24%.<br>
Die wissenschaftliche Literatur präsentiert heterogene Befunde bezüglich des Einflusses steigender Belastungsintensität auf den Nettowirkungsgrad beim Radfahren. Während @Luhtanen1987 und @Henry1950 einen Abfall des η~Netto~ mit steigender Intensität dokumentierten, berichtete @Gaesser1975 einen Anstieg. @Harnish2007 dokumentierte sowohl im Sitzen als auch im Stehen einen Anstieg des η~Netto~ mit zunehmender Intensität. In der vorliegenden Untersuchung manifestierte sich dieser Anstieg deskriptiv ausschließlich in der Stehposition, mit einer systematischen Progression von 24.70% über 25.12% zu 25.39% für die leichte bis schwere Intensitätsstufen, die potenziell statistische Relevanz aufweisen könnte, jedoch nicht inferenzstatistisch getestet wurde. In der sitzenden Position zeigte sich lediglich ein minimaler systematischer Anstieg. Nach @Gaesser1975 und @Dickinson1929 führen erhöhte Drehzahlen zu einer Reduktion des η~Netto~. Die komparative Analyse zwischen Sitz- und Stehposition als Indikator der Drehzahlabhängigkeit offenbarte hier jedoch keine signifikanten Unterschiede.

Der Gesamtwirkungsgrad (η~Total~) bewegte sich zwischen 19.77% und 24.72% (M = 22.19%) und zeigte damit ähnliche Größenordnungen wie der Bruttowirkungsgrad. Mit steigender Intensität war eine leichte Abnahme von 22.35% bei leichter zu 22.01% bei schwerer Belastung zu verzeichnen. Ein Vergleich mit Literaturwerten war nicht möglich, da bei Wirkungsgradberechnungen beim Radfahren üblicherweise entweder der Brutto- oder Nettowirkungsgrad ohne Einbezug der anaeroben-laktaziden und anaeroben-alaktaziden Energiebereitstellung bestimmt wurde.

Die für die sitzende Position ermittelten η~Arbeit~-Werte ordnen sich mit durchschnittlich 25.91 ± 1.39% in den unteren Bereich der von @Gaesser1975 berichteten Spannweite (25-28%) ein. 
Die beobachtete signifikante Reduktion des η~Arbeit~ mit zunehmender Belastungsintensität steht dabei im Kontrast zu den von @Gaesser1975 dokumentierten Effekten, bei denen ein steigender Arbeitswirkungsgrad mit steigender Belastung gezeigt wurde. In der vorliegenden Untersuchung wurde ein signifikanter Effekt der Intensität festgestellt. Die Post-hoc-Analysen zeigten signifikante Unterschiede zwischen der leichten und schweren sowie zwischen der moderaten und schweren Intensität, wobei signifikant höhere Werte bei niedrigeren Intensitäten auftraten. Dies ist wahrscheinlich auf die bei gleicher Drehzahl konstant bleibende Arbeit für die Leerbewegung (W~Leerbewegung~) sowie W~Ruhe~ zurückzuführen, welche bei steigender mechanischer Leistungsabgabe sowie steigendem Gesamtenergieumsatz proportional eine immer geringere Rolle einnehmen.
Anzumerken ist, dass der in dieser Studie bestimmte Arbeitswirkungsgrad wie auch der η~Total~ die anaeroben-laktaziden und anaeroben-alaktaziden Energiekomponenten einbezog, was in der Literatur üblicherweise nicht erfolgte. Ein Ausschluss dieser Energiekomponenten hätte zu einem höheren Arbeitswirkungsgrad geführt. Des Weiteren wurde der $\Delta\dot{V}O_{2,\text{unloaded}}$ in dieser Untersuchung mit Hilfe des Drehzahltests bestimmt und nicht wie in anderen Untersuchungen durch direkte Messungen des $\dot{V}O_{2,\text{unloaded}}$ bei bestimmten Drehzahlen oder durch die Extrapolation des y-Achsenabschnitts der linearen $\Delta\dot{V}O_{2,\text{net}} - \Delta P_{\text{mech}}$ Beziehung.

::: {.callout-note collapse="true"}
### Tabellarische Übersicht unterschiedlich berechneter Wirkungsgrade

```{r}
#| label: tbl-Wirkungsgrad
#| tbl-cap-location: top
#| tbl-cap:  "Tabellarische Übersicht unterschiedlich berechneter Wirkungsgrade beim Fahrradfahren unter verschiedenen Bedingungen"

library(flextable)
library(dplyr)
library(officer)

ft_Wirkungsgrad <- readRDS("rds/ft_Wirkungsgrad.rds")

# Anzeigen der Tabelle
ft_Wirkungsgrad
```
:::

## Limitationen & Ausblick

### Methodische Aspekte

Eine bedeutende Limitation der vorliegenden Studie stellt die geringe finale Stichprobengröße von lediglich neun Probanden dar, von denen zudem nur zwei weiblich waren. Zwar absolvierten initial 24 Probanden den ersten Testtag, jedoch wurden aufgrund der Zielsetzung, eine gut trainierte Stichprobe mit einer maximalen Sauerstoffaufnahme von über 65 ml·min^-1^·kg^-1^ zu untersuchen, nur elf Probanden in die weitere Studie eingeschlossen. Von diesen elf mussten zwei weitere Probanden aufgrund von Messfehlern oder fehlenden Messwerten ausgeschlossen werden. Diese eingeschränkte finale Probandenzahl und das unausgewogene Geschlechterverhältnis limitieren die statistische Aussagekraft der Ergebnisse und deren Generalisierbarkeit auf die Gesamtpopulation. Eine geschlechterspezifische Analyse war aufgrund der geringen Anzahl weiblicher Probandinnen nicht möglich. Zudem führte die kleine Stichprobengröße dazu, dass selbst mittlere bis große Effektstärken aufgrund der geringen statistischen Power in manchen Fällen nicht das Signifikanzniveau erreichten, wodurch potenziell bedeutsame Unterschiede statistisch nicht nachgewiesen werden konnten.

Eine weitere Limitation der vorliegenden Studie betrifft die Bestimmung der ventilatorischen Schwellen durch das verwendete 30-Sekunden-Stufenprotokoll. In einer Voruntersuchung an zwei Probanden zeigte sich im Vergleich zu einem konventionellen Stufenprotokoll mit 3-minütigen Stufen (jeweils 20 Watt Steigerung), dass die erste ventilatorische Schwelle (VT~1~) im 30-Sekunden-Protokoll im Durchschnitt etwa 30 Watt höher bestimmt wurde. Für die zweite ventilatorische Schwelle (VT~2~) fiel diese Differenz mit etwa 70 Watt noch deutlicher aus. Obwohl diese systematische Überschätzung der Schwellenwerte bei der Berechnung der Belastungsintensitäten berücksichtigt wurde, zeigten sich Limitationen in der gewählten Intensitätsabstufung.<br>
Die analysierten Belastungsintensitäten führten zu durchschnittlichen Steady-State-Werten des $\dot{V}O_{2}$ von 73.0% (leicht), 80.2% (moderat) und 89.1% (schwer) des im Stufentest ermittelten maximalen Sauerstoffvolumenstroms ($\dot{V}O_{2,max}$). Die als "leicht" klassifizierte Intensität erwies sich mit 73.0% der $\dot{V}O_{2,max}$ jedoch als problematisch in zweifacher Hinsicht: Einerseits war sie zu hoch, um sie eindeutig von der moderaten Intensität abzugrenzen, andererseits lag sie deutlich über dem für leichte Intensitäten typischen Bereich, da sie die erste ventilatorische Schwelle (VT~1~) überschritt, welche in der sportwissenschaftlichen Praxis typischerweise zwischen 55% und 70% der individuellen $\dot{V}O_{2,max}$ liegt [@Gullich2013,176]. Dies bestätigte sich auch durch den durchschnittlichen Anstieg der Blutlaktatkonzentration um 1.77 mmol·l^-1^, der auf eine Überschreitung der aeroben Schwelle hindeutet. Für weiterführende Untersuchungen wäre daher entweder die Integration einer zusätzlichen, niedrigeren Intensitätsstufe oder die Implementierung einer generell niedriger gewählten leichten Intensität empfehlenswert. Dies würde eine präzisere Differenzierung der Effekte ermöglichen und fundiertere Erkenntnisse über das Verhalten der Wirkungsgrade sowie physiologischen Belastungsparameter im tatsächlich niedrigen Intensitätsbereich liefern.

#### Vor- und Nachbelastung bei 50 Watt

Eine weitere methodische Einschränkung betrifft die Wahl der Belastung in den Vor- und Nachbelastungsphasen von 50 Watt statt einer kompletten Ruhephase. Diese Entscheidung einer aktiven Nachbelastungsphase wurde getroffen, da es in den Pilotierungen zu Kreislaufproblemen und Unwohlsein kam. Dies führte jedoch zu mehreren methodischen Herausforderungen:<br>
Die Verwendung einer leichten Belastung von 50 Watt in den Erholungsphasen anstelle einer kompletten Entlastung (0 Watt) führte zu einem erhöhten $\dot{V}O_2$ in der Nachbelastung. Dies machte eine Anpassung der in der Literatur üblichen EPOC-Modellierung erforderlich, was möglicherweise eine Fehlerquelle bei der Bestimmung des anaerob-alaktaziden Energieanteils darstellt.<br>
Die gewählte Nachbelastung beeinflusste die Kinetik des $\dot{V}O_2$ sowohl in der Vor- als auch in der Nachbelastungsphase deutlich. Durch die Vorbelastung kam es zu einer schnelleren Anpassung auf das Steady State sowie einer geringeren Amplitude der Änderung des $\dot{V}O_2$ bis zum Erreichen des Steady States. Dies führte zu einer geringeren Entleerung und Wiederauffüllung der körpereigenen Sauerstoffspeicher, als es aus der Ruhe der Fall gewesen wäre [@DiPrampero1983], was wiederum den bestimmten Anteil der anaeroben-alaktaziden Energiebereistellung beeinflusste.<br>
Zusätzlich wurde die Trittrate in dieser Nachbelastungsphase nicht kontrolliert bzw. vorgegeben, was wiederum zu inkonsistenten $\dot{V}O_2$-Werten in der Nachbelastungsphase geführt haben kann.<br>
Abschließend muss auf technische Probleme mit dem Ergometer hingewiesen werden. Sporadisch auftretende Aussetzer führten dazu, dass in den Nachbelastungsphasen zeitweise kein Tretwiderstand vorhanden war, anstelle der vorgesehenen 50 Watt. Diese Störungen, die sich über mehrere Minuten erstrecken konnten, resultierten möglicherweise in einem niedrigeren $\dot{V}O_2$ als eigentlich intendiert. Dies könnte die EPOC-Berechnung in einzelnen Fällen verfälscht haben. Da eine exakte zeitliche und fallbezogene Dokumentation dieser Störungen nicht möglich war, konnten diese bei der EPOC-Berechnung nicht berücksichtigt werden. Allerdings lagen die bestimmten W~PCr~-Werte, bis auf drei Werte an der oberen Grenze des physiologisch Plausiblen, alle im erwarteten Referenzbereich.

Als problematisch erwies sich zudem die relativ kurze Erholungszeit von 10 Minuten zwischen den einzelnen Belastungen. Diese Zeitspanne war insbesondere am zweiten Testtag nach dem Sprinttest nicht ausreichend, um eine Rückkehr der physiologischen Parameter (Herzrate, Blutlaktat, $\dot{V}O_2$) auf das Ausgangsniveau zu gewährleisten. Besonders kritisch ist dies im Hinblick auf die Laktatkonzentration zu sehen, da kein vollständiger Abbau vor Beginn der nächsten Belastung erfolgen konnte. Längere Regenerationsphasen wären hier vorteilhaft gewesen, auch für die Messung der EPOC-Kinetik, welche in dem beschriebenen Vorgehen auf über eine Stunde extrapoliert wurde aufgrund der nur 10-minütigen Nachbelastungsphase.


### Innere Arbeit/Leistung

Bei der Berechnung der inneren Leistung im Stehen muss kritisch angemerkt werden, dass diese möglicherweise unterschätzt wurde. Die angewandte Berechnungsmethodik der P~Int~ ergab zwar leicht höhere Werte im Stehen als im Sitzen bei identischer Drehzahl. Allerdings resultierten daraus signifikant niedrigere absolute P~Int~-Werte im Stehen, da dort die Trittraten in den gleichen Belastungsintensitäten signifikant geringer waren. Diese Beobachtung steht jedoch im Widerspruch zu den übrigen erhobenen Parametern: Weder die verschiedenen Wirkungsgrade (η~Total~, η~Netto~ und η~Brutto~, alle ohne Einbezug der P~Int~) noch andere physiologische Kenngrößen wie Herzrate oder $\dot{V}O_2$ zeigten bei vergleichbarer mechanischer Leistung signifikante Unterschiede zwischen stehender und sitzender Position. Dies legt nahe, dass die innere Leistung in beiden Bedingungen bei den jeweiligen durch die Probanden gewählten Drehzahlen eigentlich vergleichbar sein müsste - ein Befund, der durch die gewählten Berechnungsmethoden nicht abgebildet wurde.
Insbesondere wurden zwei wichtige Aspekte nicht berücksichtigt: Zum einen die erhöhte isometrische Haltearbeit der posturalen Muskulatur und zum anderen die vertikalen Oszillationen des Oberkörperschwerpunktes während der Tretbewegung im Stehen. 
In einer explorativen Analyse wurde zusätzlich eine Berechnung nach dem Modell von @Winter1979 durchgeführt (P~Int,Winter~), welches die vertikalen Schwerpunktänderungen der Segmente miteinbezieht. Die Ergebnisse der P~Int,Winter~ im Stehen lagen nun jedoch deutlich über den berechneten P~Int,Winter~-Werten für denselben Datensatz im Sitzen. Entgegen der auf Basis physiologischer Belastungsparameter erwarteten Äquivalenz zwischen Stehen und Sitzen der gleichen Belastungsintensität, waren die P~Int,Winter~-Werte nach diesem Berechnungsmodell im Stehen deutlich erhöht.<br>
Diese Ergebnisse deuten darauf hin, dass das entwickelte Modell für die stehende Position noch Optimierungsbedarf aufweist. Eine mögliche Ursache könnte in der Überschätzung der potentiellen Energieänderungen des HAT-Segments liegen, die einen erheblichen Anteil der Gesamtenergieänderungen ausmachen. Die transversalen Bewegungen des Oberkörpers in Richtung des jeweiligen Druckbeins und die damit verbundenen Schwerpunktverschiebungen, welche vielleicht fälschlicherweise als Änderungen der potentiellen Energie des HAT-Segments in der 3D-Kinematik erfasst wurden, könnten die unerwartet hohen P~Int~-Werte eventuell erklären. Zudem könnten Ungenauigkeiten bei der Bestimmung der Körpersegmentmassen und -schwerpunkte für die 3D-Bewegungsanalyse eine Rolle spielen, da diese lediglich anhand anthropometrischer Tabellenwerte für Länge, Masse und Schwerpunktlage festgelegt wurden [@Winter2009,88]. Eine individuelle Bestimmung dieser Parameter mittels bildgebender Verfahren und genauer anthropometrischer Messungen führt möglicherweise zu besseren Ergebnissen. Eine Anpassung der Segmentmassen unter Berücksichtigung der tatsächlichen Gewichtsverteilung zwischen Sattel und Lenker könnte möglicherweise zu den erwarteten, zwischen Sitzen und Stehen vergleichbaren P~Int~-Werten führen. Eine Messung der vertikalen und horizontalen Kräfte am Lenker während des Fahrens im Sitzen und Stehen wäre eine mögliche Hilfe bei der präziseren Bestimmung der Segmentmassenverteilung. Weitere Untersuchungen sind jedoch erforderlich, um ein valides Modell zur Berechnung der inneren Arbeit in stehender Position zu entwickeln.

Ein möglicher Ansatz zur Validierung von zukünftigen P~Int~-Modellberechnungen im Stehen ist analog zu @Ferguson2002, vor Durchführung der Tests eine definierte Gesamtleistung (P~TOT~) als Summe der inneren und externen mechanischen Leistung festzulegen: $P_{TOT} = P_{mech} + P_{Int}$. Die erforderliche innere Arbeit wird für die Probanden dann abhängig von der vorgegebenen Trittrate a priori mittels einer P~Int~-Modellberechnungen ermittelt. Verschiedene Kombinationen aus Drehzahlen und Vorgaben der mechanischen Leistung, die jeweils zur gleichen Gesamtleistung führen, werden dann verglichen. Beispielsweise wird bei Trittraten von 60 bzw. 100 Umdrehungen pro Minute die innere Leistung auf 10 bzw. 100 Watt und die entsprechende mechanische Leistung auf 240 bzw. 150 Watt festgelegt, um in beiden Bedingungen eine P~TOT~ von 250 Watt zu erreichen.
Dieser methodische Ansatz ließe sich auch zur Validierung der Berechnung der inneren Arbeit im Stehen nutzen, indem identische P~TOT~ anhand von Berechnungen der inneren Leistung bei verschiedenen Drehzahlen im Stehen und Sitzen verglichen werden. Theoretisch sollten die physiologischen Reaktionen auf die jeweiligen Belastungen übereinstimmen, sofern die innere Arbeit korrekt modelliert und berechnet wurde.

Eine weitere Berechnungsmethode zur Bestimmung der W~Int~ beim Fahren im Stehen ist ein Ansatz analog zur Bestimmung des Delta-Wirkungsgrades bzw. der $\Delta\dot{V}O_{2,\text{unloaded}}$ für das Fahren im Stehen. Hierbei wird bei konstanter Trittrate und verschiedenen Belastungsintensitäten der y-Achsenabschnitt der linearen $\Delta\dot{V}O_{2,\text{net}} - \Delta P_{\text{mech}}$ Regression extrapoliert, wie im Abschnitt "Innere Arbeit: Berechnungsmethoden auf Basis metabolischer Messungen" beschrieben. Diese Methodik könnte messbare Werte für die innere Arbeit im Stehen liefern und als Vergleichswerte für zukünftige Berechnungsmodelle der W~Int~ im Stehen fungieren [@Hintzy-Cloutier2003].

Eine genauere Untersuchung der Torque Efficiency und der negativen Leistung könnte weitere interessante Erkenntnisse liefern, insbesondere hinsichtlich des Zusammenhangs zwischen negativer Leistung und verschiedenen Wirkungsgraden. Auch der Einfluss hoher Leistungsspitzen, wie sie beim Fahren im Stehen auftreten, auf Ermüdung und Wirkungsgrad erscheint hier relevant. Die geringere Pedal Smoothness bei hohen Leistungsspitzen könnte eventuell trotz gleicher Wirkungsgrade zu schnellerer Ermüdung führen. @Burnley2012 zeigten bereits, dass Aktivitäten oberhalb eines kritischen Schwellenwerts deutlich schnellere neuromuskuläre Ermüdung auftritt. Die weitere Erforschung dieses Parameters erscheint in diesem Kontext vielversprechend.

Ein weiterer Aspekt, welcher in dieser Untersuchung nicht erforscht wurde, ist der Anteil der aufgebrachten chemischen Energie, der nicht in mechanische oder innere Arbeit umgesetzt wird. Ein Großteil dieser Energie wird in Wärmeenergie umgewandelt. Hier besteht weiterer Untersuchungsbedarf, wie dieser Anteil der Energieumwandlung in Wärmeenergie gemessen werden kann, um die Wirkungsgradberechnungen durch den Anteil der als Wärme umgewandelten Energie zu validieren oder sogar darüber direkt den Wirkungsgrad zu bestimmen.

## Relevanz der Forschungsergebnisse für die Praxis

Das Fahren im Stehen stellt auf Basis der vorliegenden Ergebnisse bezüglich des Wirkungsgrades eine valide Alternative zum Sitzen dar, um kurzzeitig die Körperposition zu variieren und unterschiedliche Muskelgruppen zu belasten. Da sich mit Ausnahme des muskulären Wirkungsgrades nichts zwischen den Bedingungen unterscheidet und der Wirkungsgrad sogar stets ein wenig höher war als im Sitzen, wenn auch nie signifikant.
Der gemittelte muskuläre Wirkungsgrad über alle Intensitäten in stehender Position ist zwar niedriger als im Sitzen, jedoch eignet sich dieser Wirkungsgrad, wie bereits diskutiert, für die Bewertung der stehenden Position in dieser Studie nur bedingt.

Ein entscheidender, in dieser Studie nicht berücksichtigter Aspekt beim Radfahren in der Praxis ist der signifikante Anstieg des Luftwiderstands beim Wechsel von sitzender zu stehender Position. Dieser kann besonders bei Profiradsportlern, die hohe Geschwindigkeiten sowohl auf ebenen Strecken als auch in bergigem Terrain erreichen, zu einer substantiellen Reduktion der Geschwindigkeit bei gleichbleibender mechanischer Leistung führen. 
Daher erscheint das Fahren im Stehen in der Praxis primär für kurze Zeitintervalle an steilen Anstiegen oder in Situationen mit geringer Geschwindigkeit sinnvoll, bei denen der Luftwiderstand gegenüber der Gravitationskraft oder dem Rollwiderstand eine untergeordnete Rolle spielt.
Eine Ausnahme stellen dabei möglihcerweise Situationen dar, in denen kurzzeitig sehr hohe mechanische Leistungen erforderlich sind, da gemäß vorliegender Literatur im Stehen über kurze Zeiträume eine höhere mechanische Leistung generiert werden kann.  Zudem ist zu beachten, dass die hier ermittelten Werte aufgrund der unterschiedlichen Bedingungen zwischen Labor- und Feldsituation abweichen können, da insbesondere beim Wiegetritt auf dem Fahrrad zusätzliche Freiheitsgrade in der Bewegungsausführung existieren, die am Ergometer nicht abgebildet werden können.

#### **Fazit**
Diese Untersuchung stellt einen ersten systematischen Ansatz dar, die Effizienz zwischen sitzender und stehender Fahrposition unter Einbeziehung der inneren Arbeit zu vergleichen. Die Ergebnisse liefern bereits wichtige Einblicke in die positionsspezifischen Unterschiede, jedoch bedarf es weiterer methodischer Entwicklungen, insbesondere bei der validen Bestimmung der inneren Arbeit im Stehen, um in zukünftigen Studien noch präzisere Vergleiche des muskulären Wirkungsgrads zwischen den Fahrpositionen zu ermöglichen.

# Quellenverzeichnis

::: {#refs}
:::
