---
title: "Forschungsfragen & Hypothesen"

execute:
  message: false
  echo: false
  warning: false
  error: false
  
bibliography: references.bib
lang: de
number-sections: false  
jupyter: false
engine: knitr
---

```{css}
#| echo: false
p {
  text-align: justify
}
caption, .figure-caption {
  text-align: left;
}
figure.quarto-float-tbl figcaption {
  text-align: left !important;
}

```

## Fragestellung und Forschungsfrage

Der aktuelle Forschungsstand zu den Unterschieden physiologischer Belastungsparameter und des Wirkungsgrades zwischen sitzender und stehender Fahrposition beim Radfahren ist limitiert. Die vorhandenen Studien untersuchten dabei vorrangig die physiologischen Belastungsparameter Herzrate und Blutlaktat sowie die respiratorischen Parameter $\dot{V}O_{2}\,(t)$, $\dot{V}CO_{2}\,(t)$ und die pulmonale Ventilation ($\dot{V}E\,(t)$). Die bisherigen Untersuchungen zum Wirkungsgradvergleich zwischen sitzender und stehender Position zeigen ein differenziertes Bild, wobei bei niedrigen und moderaten Intensitäten sowohl Brutto- als auch Nettowirkungsgrade im Stehen signifikant niedrigere Werte aufweisen, begleitet von signifikant höheren physiologischen Belastungsparametern ($\dot{V}O_{2}$ und HR) [@Ryschon1991a; @Tanaka1996a; @Berkemeier2020]. Diese Unterschiede gleichen sich jedoch bei Intensitäten über etwa 80% der $\dot{V}O_{2,max}$ zwischen den Positionen an [@Arkesteijn2016; @Harnish2007; @Millet2002; @Hansen2008; @Tanaka1996a].<br> 
Methodisch basierten diese Studien ausschließlich auf der Messung von $\dot{V}O_{2}$ und $\dot{V}CO_{2}$ zur Bestimmung des physiologischen Energieumsatzes, wobei entweder η~brutto~ [@Carlsson2024; @Millet2002; @Bouillod2014] oder η~netto~ [@Harnish2007] berechnet wurde. Bei den Untersuchungen der Wirkungsgrade über verschiedene Bedingungen sowie teils verschiedene Intensitätsstufen [@Carlsson2024; @Millet2002; @Harnish2007] konnte nur in der Studie von @Bouillod2014 ein im Mittel signifikanter Unterschied zwischen den Sitz- und Stehpositionen nachgewiesen werden. <br> Eine wesentliche methodische Einschränkung der vorliegenden Wirkungsgradbestimmungen liegt in der ausschließlichen Erfassung des aeroben Energieumsatzes unter Vernachlässigung anaerob alaktazider und laktazider Komponenten. Die in dieser Studie berechneten Wirkungsgrade η~Total~ und η~muskulär~ berücksichtigen hingegen sowohl aerobe als auch anaerobe Energieanteile.<br> η~muskulär~ adressiert zusätzlich eine methodische Limitation der Wirkungsgrade η~brutto~, η~netto~ und η~Total~, die in der Vernachlässigung der inneren Arbeit der zyklischen Beinbewegung liegt. Diese stellt neben der mechanischen Arbeit gegen das Bremsmoment eine Komponente der zu erbringenden mechanischen Gesamtarbeit beim Radfahren dar. Da die innere Arbeit mit steigender Trittrate deutlich ansteigt, zeigen η~brutto~, η~netto~ und η~Total~ besonders bei sehr hohen Drehzahlen eine deutliche Drehzahlabhängigkeit. Der η~muskulär~ integriert die innere Arbeit in die Berechnung der mechanischen Gesamtarbeit und weist keine Trittratenabhängigkeit auf [@Boning2017].

Nach dem Wissen des Autors existieren derzeit keine empirischen Untersuchungen, die den η~muskulär~ zwischen sitzender und stehender Fahrposition systematisch vergleichen. Die vorliegende Studie adressiert diese Forschungslücke mit der zentralen Fragestellung, inwiefern sich der muskuläre Wirkungsgrad bei leichter, moderater und schwerer Belastungsintensität zwischen den Fahrpositionen unterscheidet.

## Hypothese

Basierend auf den Forschungsfragen und der dargestellten Literatur wurde folgende Hypothese formuliert:

Es wird erwartet, dass die Unterschiede des muskulären Wirkungsgrades zwischen den Fahrpositionen intensitätsabhängig sind. Die Annahme ist, dass sich bei leichter Belastungsintensität der muskuläre Wirkungsgrad signifikant zwischen sitzender und stehender Position unterscheidet, während bei moderater und schwerer Intensität keine signifikanten Unterschiede des muskulären Wirkungsgrades zwischen den Fahrpositionen vermutet werden.<br>
Der muskuläre Wirkungsgrad beschreibt das Verhältnis zwischen der über den Belastungszeitraum summierten inneren und externen Arbeit zur Summe der aeroben und anaeroben metabolischen Arbeit abzüglich der Arbeit des Ruheumsatzes (@tbl-Wirkungsgrad_Berechnungen).

#### **Explorative Analysen**

Zur weiterführenden Untersuchung der formulierten Hypothesen sowie zur Identifikation und Charakterisierung potentieller Wirkmechanismen wurden ergänzende komparative Analysen durchgeführt. Diese zielten darauf ab, mögliche Unterschiede zwischen den verschiedenen Intensitäten und Bedingungen mechanistisch zu erklären. <br>
Nach identischem statistischem Vorgehen und auf Basis der gleichen Hypothese erfolgte die systematische Evaluation mehrerer Wirkungsgrade sowie deren zugrundeliegender physiologischer und mechanischer Energiekomponenten. Dies umfasste die Analyse des Gesamtwirkungsgrades (η~Total~), Nettowirkungsgrades (η~Netto~) sowie Bruttowirkungsgrades (η~Brutto~). Der Arbeitswirkungsgrad (η~Arbeit~) unterlag einer separaten Analyse hinsichtlich der Belastungsintensität. Außerdem wurden explorativ die eben genannten Parameter zwischen sitzender und stehender Position unabhängig von der Intensität verglichen (@tbl-Wirkungsgrad_Berechnungen).


::: {.callout-note collapse="true"}
#### Tabelle 1: Vergleich der Wirkungsgradberechnungen

| Wirkungsgrade |                   Berechnung                   |
|---------------|:----------------------------------------------:|
| η~Brutto~     |               W~mech~ / W~Aerob~               |
| η~Netto~      |         W~mech~ / (W~Aerob~ - W~Ruhe~)         |
| η~Total~      |          W~mech~ / (W~Tot~ - W~Ruhe~)          |
| η~muskulär~   |    (W~mech~ + W~Int~) / (W~Tot~ - W~Ruhe~)     |
| η~Arbeit~     | W~mech~ / (W~Tot~ - W~Ruhe~ - W~Leerbewegung~) |
| η~delta~      |               ΔW~mech~ / ΔW~Tot~               |

: Modifizierte Berechnungswege der Wirkungsgrade nach Gaesser und Brooks (1975), Luhtanen et al. (1987) und
Böning et al. (2017), ergänzt um den Gesamtwirkungsgrad (η~Total~). {#tbl-Wirkungsgrad_Berechnungen
tbl-colwidths="\[30,70\]" .hover}

:::


## Quellenverzeichnis

::: {#refs}
:::

