---
title: "Theoretischer Hintergrund"

execute:
  message: false
  engine: knitr
  echo: false
  warning: false
  error: false
  
bibliography: references.bib
lang: de
number-sections: false
---


```{css}
#| echo: false
p {
  text-align: justify
}
caption, .figure-caption {
  text-align: left;
}
figure.quarto-float-tbl figcaption {
  text-align: left !important;
}
figure figcaption {
  text-align: justify;
}
```

Radfahren gehört zu den effizientesten Formen der Fortbewegung die der Mensch aus eigener Kraft ausführen kann. Verglichen mit dem Laufen wird beim Radfahren ein wesentlich größerer Teil der aufgewendeten Energie in Vortrieb umgewandelt. Diese hervorragende mechanische Effizienz macht das Fahrrad nicht nur zu einem praktischen Verkehrsmittel im Alltag, sondern spielt auch im Leistungssport eine entscheidende Rolle. Gerade im Wettkampf, wo bereits kleinste Effizienzunterschiede zwischen Sieg und Niederlage entscheiden können, ist diese Eigenschaft von besonderer Bedeutung [@Beneke2001].<br>
Die Effizienz der Umwandlung von zugeführter metabolischer Energie in Vortrieb beim Radfahren lässt sich durch den Wirkungsgrad quantifizieren. Dieser beschreibt das Verhältnis zwischen der erzeugten externen Arbeit und der dafür benötigten chemischen Energie des Körpers. Diese Energieumwandlung basiert auf komplexen physiologischen Prozessen: Der menschliche Körper benötigt für jede Bewegung kontinuierlich Energie, wobei nur ein Teil der chemischen Energie in externe Arbeit umgesetzt werden kann. Die übrige Energie verteilt sich auf Wärmeerzeugung, Reibungsverluste und verschiedene zelluläre Prozesse. Das Verhältnis, wie viel der zugeführten chemischen Energie tatsächlich in externe Arbeit umgewandelt wird, definiert den Wirkungsgrad. Eine Optimierung des Wirkungsgrads ermöglicht es Sportlern, bei gleichbleibendem Energieaufwand mehr Leistung zu erzeugen oder eine bestimmte Leistung mit geringerem Energieeinsatz zu erreichen [@Stegemann1991, 62; @Bader1972, 8].

Die nachfolgenden Abschnitte dieses Kapitels beschreiben zunächst die verschiedenen Methoden zur Berechnung des Wirkungsgrads beim Radfahren. Darauf aufbauend werden die erforderlichen Berechnungen des Energieumsatzes sowie der externen und internen mechanischen Arbeit detailliert erläutert. Den Abschluss bildet eine Analyse der biomechanischen und physiologischen Unterschiede zwischen sitzender und stehender Fahrposition, die den Wirkungsgrad maßgeblich beeinflussen können.

# Quellenverzeichnis

::: {#refs}
:::
