<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Wirkungsgrad – Wirkungsgrad auf dem Radergometer im Sitzen und Stehen</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-b663525e4b92bb903b2199e2d401bf36.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-a1e4c769dfb8ba454fda448df42b92ec.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-2fb225055046be9ab762d5df9ca3bfa2.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-57d81532e27bc75cb4e27d881e21697c.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script src="../site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="../site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>
<link href="../site_libs/tabwid-1.1.3/tabwid.css" rel="stylesheet">
<script src="../site_libs/tabwid-1.1.3/tabwid.js"></script>


<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">Wirkungsgrad</li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-center sidebar-header">
      <a href="../index.html" class="sidebar-logo-link">
      <img src="../images/Logo_η_3.png" alt="" class="sidebar-logo py-0 d-lg-inline d-none">
      </a>
      <div class="sidebar-tools-main">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Dunkelmodus umschalten"><i class="bi"></i></a>
</div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Forschungsfragen_Hypothesen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Forschungsfragen &amp; Hypothesen</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../Methodik/index_Methodik.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Methodik</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Methodik/Stichprobe.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Stichprobe</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Methodik/Messmethoden.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Messmethoden</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Methodik/Studiendesign.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Studiendesign</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../Ergebnisse/index_Ergebnisse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ergebnisse &amp; Statistik</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Ergebnisse/Drehzahl_Stufentests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Eingangsuntersuchungen</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Ergebnisse/VO2_Daten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phyisologische Belastungsparameter</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Ergebnisse/EPOC_Daten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Phyisologische Nachbelastungsparameter</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Ergebnisse/Ergometer_Daten.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ergometrische Leistungsparameter</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Ergebnisse/Wirkungsgrad_Statistik.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Wirkungsgrad- und Stoffwechselparameter</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Diskussion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Diskussion</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Abkuerzungsverzeichnis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Abkürzungsverzeichnis</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Quellen.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quellenverzeichnis</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="3">
    <h2 id="toc-title">Inhalt auf dieser Seite</h2>
   
  <ul>
  <li><a href="#wirkungsgrad" id="toc-wirkungsgrad" class="nav-link active" data-scroll-target="#wirkungsgrad">Wirkungsgrad</a>
  <ul class="collapse">
  <li><a href="#werte-aus-der-literatur" id="toc-werte-aus-der-literatur" class="nav-link" data-scroll-target="#werte-aus-der-literatur">Werte aus der Literatur</a></li>
  <li><a href="#limitationen-bei-wirkungsgradberechnungen" id="toc-limitationen-bei-wirkungsgradberechnungen" class="nav-link" data-scroll-target="#limitationen-bei-wirkungsgradberechnungen">Limitationen bei Wirkungsgradberechnungen</a>
  <ul class="collapse">
  <li><a href="#einfluss-der-trittrate-auf-den-wirkungsgrad" id="toc-einfluss-der-trittrate-auf-den-wirkungsgrad" class="nav-link" data-scroll-target="#einfluss-der-trittrate-auf-den-wirkungsgrad">Einfluss der Trittrate auf den Wirkungsgrad</a></li>
  <li><a href="#wirk-delta" id="toc-wirk-delta" class="nav-link" data-scroll-target="#wirk-delta">Wirk Delta</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#quellenverzeichnis" id="toc-quellenverzeichnis" class="nav-link" data-scroll-target="#quellenverzeichnis">Quellenverzeichnis</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Wirkungsgrad</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<style type="text/css">
p {
  text-align: justify
}
caption, .figure-caption {
  text-align: left;
}
figure.quarto-float-tbl figcaption {
  text-align: left !important;
}

</style>
</div>
<section id="wirkungsgrad" class="level1">
<h1>Wirkungsgrad</h1>
<p><strong>Geile Einleitung in <span class="citation" data-cites="Beneke2001">Beneke &amp; Di Prampero (<a href="#ref-Beneke2001" role="doc-biblioref">2001</a>)</span></strong></p>
<div class="columns">
<div class="column" style="width:52%;">
<p>Der Wirkungsgrad<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> definiert das Verhältnis von umgesetzter chemischer Energie zur erzeugten mechanischen Energie. Er wird üblicherweise als Dezimalzahl oder Prozentwert ausgedrückt.<br> Es existieren mehrere Möglichkeiten den Wirkungsgrad zu berechnen, darunter den Bruttowirkungsgrad (η<sub>brutto</sub>), den Nettowirkungsgrad (η<sub>netto</sub>), den Arbeitswirkungsgrad (η<sub>Arbeit</sub>) sowie den Deltawirkungsgrad (η<sub>delta</sub>) (siehe <a href="#tbl-Wirkungsgrad_Berechnungen" class="quarto-xref">Tabelle&nbsp;1</a>). Gewisse Bestimmungsverfahren ermöglichen zwar eine einfache Anwendung, können jedoch mehrere Ungenauigkeiten bzw. Einflussfaktoren beinhalten. Andere hingegen erfordern komplexere Berechnungen und eine größere Anzahl an Messdaten, liefern dafür aber präzisere Daten. In der nachfolgenden Tabelle sind verschiedene Möglichkeiten zur Wirkungsgradberechnung aufgeführt <span class="citation" data-cites="Boning2017 Luhtanen1987 Gaesser1975">(<a href="#ref-Boning2017" role="doc-biblioref">Böning et al., 2017</a>; <a href="#ref-Gaesser1975" role="doc-biblioref">Gaesser &amp; Brooks, 1975</a>; <a href="#ref-Luhtanen1987" role="doc-biblioref">Luhtanen et al., 1987</a>)</span>:</p>
</div><div class="column" style="width:2%;">

</div><div class="column" style="width:46%;">
<div id="tbl-Wirkungsgrad_Berechnungen" class="hover quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[30,70]">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-Wirkungsgrad_Berechnungen-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-hover table">
<colgroup>
<col style="width: 30%">
<col style="width: 70%">
</colgroup>
<thead>
<tr class="header">
<th>Wirkungsgrade</th>
<th style="text-align: center;">Berechnung</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>η<sub>Brutto</sub></td>
<td style="text-align: center;">P<sub>mech</sub> / E<sub>Aerob</sub></td>
</tr>
<tr class="even">
<td>η<sub>Netto</sub></td>
<td style="text-align: center;">P<sub>mech</sub> / (E<sub>Aerob</sub>&nbsp;-&nbsp;E<sub>Ruhe</sub>)</td>
</tr>
<tr class="odd">
<td>η<sub>Total</sub></td>
<td style="text-align: center;">P<sub>mech</sub> / (E<sub>Tot</sub>&nbsp;-&nbsp;E<sub>Ruhe</sub>)</td>
</tr>
<tr class="even">
<td>η<sub>muskulär</sub></td>
<td style="text-align: center;">(P<sub>mech</sub> + P<sub>Int</sub>) / (E<sub>Tot</sub>&nbsp;-&nbsp;E<sub>Ruhe</sub>)</td>
</tr>
<tr class="odd">
<td>η<sub>Arbeit</sub></td>
<td style="text-align: center;">P<sub>mech</sub> / (E<sub>Tot</sub> -&nbsp;E<sub>Ruhe</sub> -&nbsp;E<sub>Leerbewegung</sub>)</td>
</tr>
<tr class="even">
<td>η<sub>delta</sub></td>
<td style="text-align: center;">ΔP<sub>mech</sub> / ΔE<sub>Tot</sub></td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-Wirkungsgrad_Berechnungen-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;1: Modifizierte Berechnungswege der Wirkungsgrade nach Gaesser und Brooks (1975), Luhtanen et al.&nbsp;(1987) und Böning et al.&nbsp;(2017), ergänzt um den Gesamtwirkungsgrad (η<sub>Total</sub>).
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Temperaturregulation bei körperlicher Belastung bzw. wo geht die Wärmeenergie hin noch mit einbeziehen und beschrieben!!!!!!!!!!!!!! –&gt; Aschoff, Stegemann, deMaares S.552, Astrand S. 396</strong> <strong>Statt über indirekte Kaliometrie über die Wärmeabgabe den Wirkungsgrad gegenrechnen oder direkt Berechnen?????</strong></p>
<p><strong>NOCH ZUSÄTzLICH DIE BERECHNUNG VON WIRK_TOTAL MIT BESCHREBEN –&gt; VERGLICH ZWISCHEN WIRK MUSKULÄR UND TOTAL –&gt; EINFLUSS VON PINT</strong></p>
<div class="cell" data-tbl-cap-location="top">
<div id="tbl-Wirkungsgrad" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-tbl-cap-location="top">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-Wirkungsgrad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabelle&nbsp;2: Tabellarische Übersicht unterschiedlich berechneter Wirkungsgrade beim Fahrradfahren unter verschiedenen Bedingungen
</figcaption>
<div aria-describedby="tbl-Wirkungsgrad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div class="tabwid"><style>.cl-ae4f9296{table-layout:auto;width:100%;}.cl-ae47b2ce{font-family:'Source Sans Pro';font-size:12pt;font-weight:bold;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-ae47b2d8{font-family:'Source Sans Pro';font-size:11pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-ae47b2d9{font-family:'Source Sans Pro';font-size:6.6pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;position: relative;top:3.3pt;}.cl-ae47b2e2{font-family:'Arial';font-size:10pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;}.cl-ae47b2e3{font-family:'Arial';font-size:6pt;font-weight:normal;font-style:normal;text-decoration:none;color:rgba(0, 0, 0, 1.00);background-color:transparent;position: relative;top:3pt;}.cl-ae4b826e{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:4pt;padding-top:4pt;padding-left:4pt;padding-right:4pt;line-height: 1;background-color:transparent;}.cl-ae4b8278{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:4pt;padding-top:4pt;padding-left:4pt;padding-right:4pt;line-height: 1;background-color:transparent;}.cl-ae4b8282{margin:0;text-align:left;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:4pt;padding-top:4pt;padding-left:4pt;padding-right:4pt;line-height: 1.25;background-color:transparent;}.cl-ae4b8283{margin:0;text-align:center;border-bottom: 0 solid rgba(0, 0, 0, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0 solid rgba(0, 0, 0, 1.00);border-right: 0 solid rgba(0, 0, 0, 1.00);padding-bottom:4pt;padding-top:4pt;padding-left:4pt;padding-right:4pt;line-height: 1.25;background-color:transparent;}.cl-ae4ba0a0{background-color:rgba(235, 235, 235, 1.00);vertical-align: middle;border-bottom: 0.5pt solid rgba(169, 169, 169, 1.00);border-top: 0.5pt solid rgba(169, 169, 169, 1.00);border-left: 0.5pt solid rgba(169, 169, 169, 1.00);border-right: 0.5pt solid rgba(169, 169, 169, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ae4ba0aa{background-color:rgba(235, 235, 235, 1.00);vertical-align: middle;border-bottom: 0.5pt solid rgba(169, 169, 169, 1.00);border-top: 0.5pt solid rgba(169, 169, 169, 1.00);border-left: 0.5pt solid rgba(169, 169, 169, 1.00);border-right: 0.5pt solid rgba(169, 169, 169, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ae4ba0ab{background-color:rgba(249, 249, 249, 1.00);vertical-align: middle;border-bottom: 0.5pt solid rgba(211, 211, 211, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.5pt solid rgba(169, 169, 169, 1.00);border-right: 0.5pt solid rgba(169, 169, 169, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ae4ba0ac{background-color:rgba(249, 249, 249, 1.00);vertical-align: middle;border-bottom: 0.5pt solid rgba(211, 211, 211, 1.00);border-top: 0 solid rgba(0, 0, 0, 1.00);border-left: 0.5pt solid rgba(169, 169, 169, 1.00);border-right: 0.5pt solid rgba(169, 169, 169, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ae4ba0b4{background-color:rgba(255, 255, 255, 1.00);vertical-align: middle;border-bottom: 0.5pt solid rgba(211, 211, 211, 1.00);border-top: 0.5pt solid rgba(211, 211, 211, 1.00);border-left: 0.5pt solid rgba(169, 169, 169, 1.00);border-right: 0.5pt solid rgba(169, 169, 169, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ae4ba0b5{background-color:rgba(255, 255, 255, 1.00);vertical-align: middle;border-bottom: 0.5pt solid rgba(211, 211, 211, 1.00);border-top: 0.5pt solid rgba(211, 211, 211, 1.00);border-left: 0.5pt solid rgba(169, 169, 169, 1.00);border-right: 0.5pt solid rgba(169, 169, 169, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ae4ba0b6{background-color:rgba(249, 249, 249, 1.00);vertical-align: middle;border-bottom: 0.5pt solid rgba(211, 211, 211, 1.00);border-top: 0.5pt solid rgba(211, 211, 211, 1.00);border-left: 0.5pt solid rgba(169, 169, 169, 1.00);border-right: 0.5pt solid rgba(169, 169, 169, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ae4ba0be{background-color:rgba(249, 249, 249, 1.00);vertical-align: middle;border-bottom: 0.5pt solid rgba(211, 211, 211, 1.00);border-top: 0.5pt solid rgba(211, 211, 211, 1.00);border-left: 0.5pt solid rgba(169, 169, 169, 1.00);border-right: 0.5pt solid rgba(169, 169, 169, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ae4ba0bf{background-color:rgba(255, 255, 255, 1.00);vertical-align: middle;border-bottom: 0.5pt solid rgba(169, 169, 169, 1.00);border-top: 0.5pt solid rgba(211, 211, 211, 1.00);border-left: 0.5pt solid rgba(169, 169, 169, 1.00);border-right: 0.5pt solid rgba(169, 169, 169, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ae4ba0c0{background-color:rgba(255, 255, 255, 1.00);vertical-align: middle;border-bottom: 0.5pt solid rgba(169, 169, 169, 1.00);border-top: 0.5pt solid rgba(211, 211, 211, 1.00);border-left: 0.5pt solid rgba(169, 169, 169, 1.00);border-right: 0.5pt solid rgba(169, 169, 169, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ae4ba0c1{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(169, 169, 169, 1.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0.5pt solid rgba(169, 169, 169, 1.00);border-right: 0.5pt solid rgba(169, 169, 169, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ae4ba0c8{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(169, 169, 169, 1.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0 solid rgba(255, 255, 255, 0.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}.cl-ae4ba0c9{background-color:transparent;vertical-align: middle;border-bottom: 0.5pt solid rgba(169, 169, 169, 1.00);border-top: 0 solid rgba(255, 255, 255, 0.00);border-left: 0 solid rgba(255, 255, 255, 0.00);border-right: 0.5pt solid rgba(169, 169, 169, 1.00);margin-bottom:0;margin-top:0;margin-left:0;margin-right:0;}</style><table data-quarto-disable-processing="true" class="cl-ae4f9296"><thead><tr style="overflow-wrap:break-word;"><th class="cl-ae4ba0a0"><p class="cl-ae4b826e"><span class="cl-ae47b2ce">Autoren</span></p></th><th class="cl-ae4ba0aa"><p class="cl-ae4b8278"><span class="cl-ae47b2ce">Belastungsintensität</span></p></th><th class="cl-ae4ba0aa"><p class="cl-ae4b8278"><span class="cl-ae47b2ce">Trittrate [U·min⁻¹]</span></p></th><th class="cl-ae4ba0aa"><p class="cl-ae4b8278"><span class="cl-ae47b2ce">Teilnehmende</span></p></th><th class="cl-ae4ba0aa"><p class="cl-ae4b8278"><span class="cl-ae47b2ce">Berechneter η</span></p></th><th class="cl-ae4ba0aa"><p class="cl-ae4b8278"><span class="cl-ae47b2ce">Wirkungsgrad [%]</span></p></th></tr></thead><tbody><tr style="overflow-wrap:break-word;"><td class="cl-ae4ba0ab"><p class="cl-ae4b8282"><span class="cl-ae47b2d8">Dickinson &amp; Dickinson (1929)</span></p></td><td class="cl-ae4ba0ac"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">Belastungsdauer: 10 min</span></p></td><td class="cl-ae4ba0ac"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">28-111</span></p></td><td class="cl-ae4ba0ac"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">N = 1 | ♀</span></p></td><td class="cl-ae4ba0ac"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto</span></p></td><td class="cl-ae4ba0ac"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto</span><span class="cl-ae47b2d8"> = 19.0 ± 2.8%</span><br><span class="cl-ae47b2d8">→ Optimale Trittrate bei 33.3 U/min</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ae4ba0b4"><p class="cl-ae4b8282"><span class="cl-ae47b2d8">Henry &amp; DeMoor (1950)</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">113 | 150 </span><br><span class="cl-ae47b2d8">Belastungsdauer: 6 min</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">61</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">N = 9 | ♂</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto</span><span class="cl-ae47b2d8"> = 21.2% | </span><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto</span><span class="cl-ae47b2d8"> = 19.3% </span><br><span class="cl-ae47b2d8">→ Niedriger </span><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto</span><span class="cl-ae47b2d8"> bei höherer Last</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ae4ba0b6"><p class="cl-ae4b8282"><span class="cl-ae47b2d8">Gaesser &amp; Brooks (1975)</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">32.7 | 65.4 | 98.1 | 130.8 </span><br><span class="cl-ae47b2d8">Belastungsdauer: 6-8 min</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">40 | 60 | 80 | 100</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">N = 12 | 19-24 Jahre | ♂</span><br></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">Arbeit</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">Delta</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">40,brutto</span><span class="cl-ae47b2d8"> = 12-20 | η</span><span class="cl-ae47b2d9">60,brutto</span><span class="cl-ae47b2d8"> = 12-20 | η</span><span class="cl-ae47b2d9">80,brutto</span><span class="cl-ae47b2d8"> = 10-19 | η</span><span class="cl-ae47b2d9">100,brutto</span><span class="cl-ae47b2d8"> = 8-17</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">40,netto</span><span class="cl-ae47b2d8"> = 19-24 | η</span><span class="cl-ae47b2d9">60,netto</span><span class="cl-ae47b2d8"> = 19-24 | η</span><span class="cl-ae47b2d9">80,netto</span><span class="cl-ae47b2d8"> = 15-22 | η</span><span class="cl-ae47b2d9">100,netto</span><span class="cl-ae47b2d8"> = 10-19</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">40,Arbeit</span><span class="cl-ae47b2d8"> = 25-26 | η</span><span class="cl-ae47b2d9">60,Arbeit</span><span class="cl-ae47b2d8"> = 26-27 | η</span><span class="cl-ae47b2d9">80,Arbeit</span><span class="cl-ae47b2d8"> = 26 | η</span><span class="cl-ae47b2d9">100,Arbeit</span><span class="cl-ae47b2d8"> = 27-28</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">Delta</span><span class="cl-ae47b2d8"> = 24.4-34.0</span><br><span class="cl-ae47b2d8">→ η steigt mit steigender Belastungsintensität</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ae4ba0b4"><p class="cl-ae4b8282"><span class="cl-ae47b2d8">Seabury et al. (1977)</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">40.8 | 81.7 | 122.6 | 163.4 | 196.1 | 204.2 | 245.1 | 286.0 | 326.8 </span><br><span class="cl-ae47b2d8">Belastungsdauer: 6 min</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">42 | 46 | 50 | 54 | 58 | 59 | 61 | 62 | 64</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">N = 3 | ♂</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8"> = 15.4 | η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8"> = 19.2 | η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8"> = 20.9 | η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8"> = 21.9 | η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8"> = 21.4 | η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8"> = 22.6 | η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8"> = 23.0 | η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8"> = 23.4 | η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8"> = 23.6</span><br><span class="cl-ae47b2d8">→ Steigender </span><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8"> bei höherer Last</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ae4ba0b6"><p class="cl-ae4b8282"><span class="cl-ae47b2d8">Suzuki (1979)</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">20-80% V̇O₂ₘₐₓ</span><br><span class="cl-ae47b2d8">Belastungsdauer: 15 min</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">60 | 100</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">N = 6 </span><br><span class="cl-ae47b2d8"> 3ST: 78% ST-Fasern &amp; 3FT: 76% FT-Fasern | 32.0 ± 5.6 Jahre | ♂</span><br><span class="cl-ae47b2d8">LN: 2-4</span><br><span class="cl-ae47b2d8">V̇O₂ₘₐₓ = 60.7 ± 5.7 [l·min⁻¹·kg⁻¹]</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">Delta</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">ST-Gruppe:</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">Delta, 60</span><span class="cl-ae47b2d8"> = 23.3 ± 0.9</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">Delta, 100</span><span class="cl-ae47b2d8"> = 19.6 ± 1.6</span><br><span class="cl-ae47b2d8">FT-Gruppe:</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">Delta, 60</span><span class="cl-ae47b2d8"> = 25.3 ± 2.3</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">Delta, 100</span><span class="cl-ae47b2d8"> = 28.8 ± 1.0</span><br><span class="cl-ae47b2d8">→ η</span><span class="cl-ae47b2d9">Delta</span><span class="cl-ae47b2d8"> sinkt/steigt in ST-Gruppe/FT-Gruppe mit steigender Trittrate</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ae4ba0b4"><p class="cl-ae4b8282"><span class="cl-ae47b2d8">Luhtanen et al. (1987)</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">50% V̇O₂ₘₐₓ | AerT | AnT | AnT + 30 Watt | AnT + 60 Watt</span><br><span class="cl-ae47b2d8">Belastungsdauer: 5 min</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">60</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">N = 12 | 21-38 Jahre | ♂</span><br><span class="cl-ae47b2d8">LN: 3</span><br><span class="cl-ae47b2d8">V̇O₂ₘₐₓ = 59.6 ± 2.5 [l·min⁻¹·kg⁻¹]</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">Arbeit</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8"> = 17.4 ± 1.0 - 19.7 ± 2.8</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto</span><span class="cl-ae47b2d8"> = 17.5 ± 0.7 - 21.8 ± 2.4</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">Arbeit</span><span class="cl-ae47b2d8"> = 21.0 ± 1.5 - 29.7 ± 4.2</span><br><span class="cl-ae47b2d8">→ η sinkt mit steigender Belastungsintensität</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ae4ba0b6"><p class="cl-ae4b8282"><span class="cl-ae47b2d8">Francescato et al. (1995)</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">20-125W </span><br><span class="cl-ae47b2d8">Belastungsdauer: 6 min</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">40 | 60 | 80 | 100</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">N = 4 | 22.2 ± 1.5 Jahre | ♂</span><br><span class="cl-ae47b2d8">LN: 1</span><br><span class="cl-ae47b2d8">V̇O₂max = 37.8 ± 4.9 [ml·min⁻¹·kg⁻¹]</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">Delta</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">Delta</span><span class="cl-ae47b2d8"> = 22.9 - 32.0</span><br><span class="cl-ae47b2d8">→ η</span><span class="cl-ae47b2d9">delta</span><span class="cl-ae47b2d8"> steigt mit steigender Trittrate</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ae4ba0b4"><p class="cl-ae4b8282"><span class="cl-ae47b2d8">Chavarren &amp; Calbet (1999)</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">54% | 63%| 73% | 80% | 87% | 93% der V̇O₂ₘₐₓ</span><br><span class="cl-ae47b2d8">Belastungsdauer: 6 min</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">60 | 80 | 100 | 120</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">N = 7 | 22-25 Jahre | ♂</span><br><span class="cl-ae47b2d8">LN: 4-5</span><br><span class="cl-ae47b2d8">V̇O₂ₘₐₓ = 67.77 ± 5.07 [l·min⁻¹·kg⁻¹]</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">Delta</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8"> = 13.0 ± 0.4 - 19.9 ± 0.7</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">Delta</span><span class="cl-ae47b2d8"> = 21.5 ± 0.8 - 23.9 ± 1.0</span><br><span class="cl-ae47b2d8">→ η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8"> steigt mit steigender Belastungsintensität</span><br><span class="cl-ae47b2d8">→ η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8"> sinkt mit steigender Drehzahl</span><br><span class="cl-ae47b2d8">→ η</span><span class="cl-ae47b2d9">Delta</span><span class="cl-ae47b2d8"> steigt mit steigender Drehzahl</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ae4ba0b6"><p class="cl-ae4b8282"><span class="cl-ae47b2d8">Beneke et al. (2002)</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">WAnT</span><br><span class="cl-ae47b2d8">ST: letzte Stufe bei 362 ± 41 Watt</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">WAnT = 80 - 170</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">N = 7 | 21.6 ± 3.8 Jahre | ♂</span><br><span class="cl-ae47b2d8">LN: 1-3; Sportartfremd: Rugby </span><br><span class="cl-ae47b2d8">V̇O₂ₘₐₓ = 51.34 ± 9.44 [l·min⁻¹·kg⁻¹]</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto, WAnT</span><span class="cl-ae47b2d8"> = 16.2 ± 1.6</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto, ST</span><span class="cl-ae47b2d8"> = 24.1 ± 1.7</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ae4ba0b4"><p class="cl-ae4b8282"><span class="cl-ae47b2d8">Millet et al. (2002)</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">75% des PPO</span><br><span class="cl-ae47b2d8">Belastungsdauer: 6 min</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">60 | 90</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">N = 8 | 20.7 ± 3.9 Jahre | ♂</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto,sitzen</span><span class="cl-ae47b2d8"> = 22.4 ± 0.8</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto,stehen</span><span class="cl-ae47b2d8"> = 22.2 ± 1.7</span><br><span class="cl-ae47b2d8">→ Keine sig. Unterschiede zw. </span><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto,stehen</span><span class="cl-ae47b2d8"> und η</span><span class="cl-ae47b2d9">brutto,sitzen</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ae4ba0b6"><p class="cl-ae4b8282"><span class="cl-ae47b2d8">Harnish et al. (2007)</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">50% | 65% | 75% | 93% des PPO</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">Sitzen: 74.6-82.4</span><br><span class="cl-ae47b2d8">Stehen: 57.0-65.8</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">N = 8 | 25.8 ± 7.2 Jahre | 7♂ 1♀</span><br><span class="cl-ae47b2d8">LN: 4-5</span><br><span class="cl-ae47b2d8">V̇O₂ₘₐₓ = 68.8 ± 5.0 [l·min⁻¹·kg⁻¹]</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto,sitzen</span><span class="cl-ae47b2d8"> = 24.2 ± 1.7 - 26.0 ± 1.7 </span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto,stehen</span><span class="cl-ae47b2d8"> = 25.1 ± 3.7 - 26.7 ± 2.3 </span><br><span class="cl-ae47b2d8">→ Keine sig. Unterschiede zw. Sitzen und Stehen</span><br><span class="cl-ae47b2d8">→  η</span><span class="cl-ae47b2d9">netto</span><span class="cl-ae47b2d8"> steigt mit steigender Belastungsintensität</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ae4ba0b4"><p class="cl-ae4b8282"><span class="cl-ae47b2d8">Bell &amp; Ferguson (2009)</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">75% der VT</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">45 | 60 | 75 | 90</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">N = 16 (8 jung / 8 alt) | 19-74 Jahre | ♀</span><br></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">muskulär</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto, jung</span><span class="cl-ae47b2d8"> = 27.5 ± 4.0 | 29.1 ± 5.1</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">netto, alt</span><span class="cl-ae47b2d8"> = 22.4 ± 6.9 | 20.7 ± 5.5</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">muskulär, jung</span><span class="cl-ae47b2d8"> = 32.0 ± 3.1 | 34.0 ± 5.5</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">muskulär, alt</span><span class="cl-ae47b2d8"> = 30.2 ± 3.1 | 27.9 ± 4.1</span><br><span class="cl-ae47b2d8">→ Muskeltemp.</span><span class="cl-ae47b2d9">normal</span><span class="cl-ae47b2d8"> | Muskeltemp.</span><span class="cl-ae47b2d9">erhöht</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ae4ba0b6"><p class="cl-ae4b8282"><span class="cl-ae47b2d8">Bouillod &amp; Pinot (2014)</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">3.8 | 4.2 | 4.6 [W·kg⁻¹]</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">-</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">N = 13</span><br><span class="cl-ae47b2d8">LN: Elite</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto, sitzen</span><span class="cl-ae47b2d8"> = 20.6 ± 1.1 </span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto, stehen</span><span class="cl-ae47b2d8"> = 21.5 ± 5.2 </span><br><span class="cl-ae47b2d8">→ Im Sitzen sig. höherer höherer  </span><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ae4ba0b4"><p class="cl-ae4b8282"><span class="cl-ae47b2d8">Dunst et al. (2023)</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">3s, 8s, 12s, 60s Maximalsprints</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">120</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">N = 12 | LN: Elite-Bahnradsportler</span><br><span class="cl-ae47b2d8">3♀: 18.7 ± 4.7 Jahre</span><br><span class="cl-ae47b2d8">9♂: 22.2 ± 4.4 Jahre</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span></p></td><td class="cl-ae4ba0b5"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8"> = 10.01 ± 2.18 (3s) - 18.42 ± 1.51 (60s)</span><br><span class="cl-ae47b2d8">→ Anstieg von </span><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8">  mit zunehmender Sprintdauer</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ae4ba0b6"><p class="cl-ae4b8282"><span class="cl-ae47b2d8">Zoladz et al. (2023)</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">30-120W</span><br><span class="cl-ae47b2d8">Belastungsdauer: 6 min</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">60</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">N = 17 | 23 ± 3 Jahre | ♂</span><br><span class="cl-ae47b2d8">LN: 1-3</span><br><span class="cl-ae47b2d8">V̇O₂max = 52.3 ± 5.5 [ml·min⁻¹·kg⁻¹]</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">Delta</span></p></td><td class="cl-ae4ba0be"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8"> = 11.6 ± 1.4 - 21.4 ± 1.1</span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">Delta</span><span class="cl-ae47b2d8"> = 29.8 ± 1.9</span><br><span class="cl-ae47b2d8">→ Steigender </span><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span><span class="cl-ae47b2d8"> bei höherer Last</span></p></td></tr><tr style="overflow-wrap:break-word;"><td class="cl-ae4ba0bf"><p class="cl-ae4b8282"><span class="cl-ae47b2d8">Carlsson et al. (2024)</span></p></td><td class="cl-ae4ba0c0"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">AerT</span><br><span class="cl-ae47b2d8">Belastungsdauer: 5 min</span></p></td><td class="cl-ae4ba0c0"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">-</span></p></td><td class="cl-ae4ba0c0"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">N = 10 | 25 ± 8 Jahre | ♂</span><br><span class="cl-ae47b2d8">LN: Elite-National</span></p></td><td class="cl-ae4ba0c0"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto</span></p></td><td class="cl-ae4ba0c0"><p class="cl-ae4b8283"><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto, sitzen</span><span class="cl-ae47b2d8"> = 21.3 ± 1.2 </span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto, stehen</span><span class="cl-ae47b2d8"> = 21.3 ± 1.1 </span><br><span class="cl-ae47b2d8">η</span><span class="cl-ae47b2d9">brutto, sitzen und stehen</span><span class="cl-ae47b2d8"> = 21.0 ± 1.1 </span><br><span class="cl-ae47b2d8">→ Keine sig. Unterschiede zw. den Bedingungen</span></p></td></tr></tbody><tfoot><tr style="overflow-wrap:break-word;"><td colspan="6" class="cl-ae4ba0c1"><p class="cl-ae4b826e"><span class="cl-ae47b2e2">WAnT: Wingate Anaerobic Test; AerT: Aerobe Schwelle; AnT: Anaerobe Schwelle; ST: Stufentest; PPO (Peak Power Output): maximale mechanische Leistung in einem Eingangstest; MAP (Maximal Aerobic Power): höchste über 1 Minute gemittelte Leistung in einem Eingangstes; </span><span class="cl-ae47b2e2">V̇O</span><span class="cl-ae47b2e3">2max</span><span class="cl-ae47b2e2"> [ml·min</span><span class="cl-ae47b2e3">-1</span><span class="cl-ae47b2e2">·kg</span><span class="cl-ae47b2e3">-1</span><span class="cl-ae47b2e2">]: maximaler Sauerstoffvolumenstrom; P</span><span class="cl-ae47b2e3">max</span><span class="cl-ae47b2e2">: maximale mechanische Leistung; </span><span class="cl-ae47b2e2">VT: Ventilatorische Schwelle; </span><span class="cl-ae47b2e2">LN: Leistungsniveau nach De Pauw et al. (2013) abhängig von der V̇O</span><span class="cl-ae47b2e3">2max</span><span class="cl-ae47b2e2"> [ml·min</span><span class="cl-ae47b2e3">-1</span><span class="cl-ae47b2e2">·kg</span><span class="cl-ae47b2e3">-1</span><span class="cl-ae47b2e2">] eingeteilt in LN1: &lt;45, LN2: 45-54.9, LN3: 55-64.9, LN4: 65-71, LN5: &gt;71</span></p></td></tr></tfoot></table></div>
</div>
</div>
</figure>
</div>
</div>
<section id="werte-aus-der-literatur" class="level2">
<h2 class="anchored" data-anchor-id="werte-aus-der-literatur">Werte aus der Literatur</h2>
<p>Die aus der Fachliteratur ausgewählten und in der <a href="#tbl-Wirkungsgrad" class="quarto-xref">Tabelle&nbsp;2</a> dargestellten Wirkungsgrade zeigen eine erhebliche Variabilität, wobei systematische Unterschiede zwischen den verschiedenen Berechnungsmethoden erkennbar sind.</p>
<p>Der Bruttowirkungsgrad (η<sub>brutto</sub>) weist konsistent die niedrigsten Werte aller berechneten Wirkungsgrade auf. Die Spannweite der gemessenen Werte reicht von unter 10% <span class="citation" data-cites="Gaesser1975 Dunst2023a">(<a href="#ref-Dunst2023a" role="doc-biblioref">Dunst et al., 2023</a>; <a href="#ref-Gaesser1975" role="doc-biblioref">Gaesser &amp; Brooks, 1975</a>)</span>, die charakteristischerweise bei extrem hoher Drehzahl, sehr geringer Last oder einer Kombination beider Faktoren auftreten, bis zu Maximalwerten von 23,6% <span class="citation" data-cites="Seabury1977">(<a href="#ref-Seabury1977" role="doc-biblioref">Seabury et al., 1977</a>)</span>, die bei hohen Lasten und moderaten Drehzahlen dokumentiert wurden. Mit typischen Werten zwischen 19% und 22% stellt sich ein charakteristischer Bereich dar, der in vielen Studien bestätigt wird. In der Regel steigt η<sub>brutto</sub> mit steigender Belastungsintensität, da hier der Anteil des Ruheenergiestoffwechsels kleiner wird und sinkt mit hohen Trittraten.</p>
<p>Der Nettowirkungsgrad (η<sub>netto</sub>) eliminiert den Einfluss des Ruheenergieumsatzes und zeigt dadurch systematisch höhere Werte als der Bruttowirkungsgrad. Die dokumentierten Werte in den Studien bewegen sich überwiegend zwischen 19% und 24%. Die Abhängigkeit von der Belastungsintensität zeigt in der Literatur unterschiedliche Effekte: Während <span class="citation" data-cites="Luhtanen1987">Luhtanen et al. (<a href="#ref-Luhtanen1987" role="doc-biblioref">1987</a>)</span> einen Abfall des η<sub>netto</sub> von 21,8% auf 17,5% und <span class="citation" data-cites="Henry1950">Henry &amp; DeMoor (<a href="#ref-Henry1950" role="doc-biblioref">1950</a>)</span> von 21,2% auf 19,3% mit steigender Intensität dokumentiert, berichten sowohl <span class="citation" data-cites="Gaesser1975">Gaesser &amp; Brooks (<a href="#ref-Gaesser1975" role="doc-biblioref">1975</a>)</span> als auch <span class="citation" data-cites="Harnish2007">Harnish et al. (<a href="#ref-Harnish2007" role="doc-biblioref">2007</a>)</span> einen Anstieg des η<sub>netto</sub> mit zunehmender Belastung. Diese gegensätzlichen Befunde könnten auf unterschiedliche Testprotokolle und Probandencharakteristika zurückzuführen sein. Ein konsistenterer Effekt zeigt sich bei der Trittrate: Hohe Drehzahlen führen hier zu einem deutlichen Abfall des η<sub>netto</sub> <span class="citation" data-cites="Gaesser1975 Dickinson1929">(<a href="#ref-Dickinson1929" role="doc-biblioref">Dickinson &amp; Dickinson, 1929</a>; <a href="#ref-Gaesser1975" role="doc-biblioref">Gaesser &amp; Brooks, 1975</a>)</span>.</p>
<p>Der Delta-Wirkungsgrad (η<sub>delta</sub>) weist mit Ausnahme von η<sub>Muskulär</sub> die höchsten Werte der verschiedenen Berechnungsmethoden auf. Die dokumentierten Werte bewegen sich typischerweise zwischen 23% und 28%. Die Spannweite reicht von Minimalwerten um 20% <span class="citation" data-cites="Suzuki1979">(<a href="#ref-Suzuki1979" role="doc-biblioref">Suzuki, 1979</a>)</span> bis zu Maximalwerten von über 32% <span class="citation" data-cites="Francescato1995">(<a href="#ref-Francescato1995" role="doc-biblioref">Francescato et al., 1995</a>)</span>. Im Gegensatz zu η<sub>brutto</sub> und η<sub>netto</sub> zeigt η<sub>delta</sub> keinen Abfall mit steigender Trittrate, da durch die Berechnungsmethode der Energieumsatz für das Pedalieren ohne Last, welcher mit steigender Drehzahl zunimmt, nicht einbezogen wird. So berichten <span class="citation" data-cites="Francescato1995">Francescato et al. (<a href="#ref-Francescato1995" role="doc-biblioref">1995</a>)</span>, <span class="citation" data-cites="Chavarren1999">Chavarren &amp; Calbet (<a href="#ref-Chavarren1999" role="doc-biblioref">1999</a>)</span> und <span class="citation" data-cites="Gaesser1975">Gaesser &amp; Brooks (<a href="#ref-Gaesser1975" role="doc-biblioref">1975</a>)</span> sogar einen Anstieg des η<sub>delta</sub> mit steigender Drehzahl. Differenzierte Ergebnisse zeigen sich bei <span class="citation" data-cites="Suzuki1979">Suzuki (<a href="#ref-Suzuki1979" role="doc-biblioref">1979</a>)</span>: Bei Probanden mit überwiegend schnellen Muskelfasern (FT) steigt η<sub>delta</sub> bei hohen Drehzahlen an, während bei Probanden mit überwiegend langsamen Muskelfasern (ST) η<sub>delta</sub> bei hohen Drehzahlen abnimmt.</p>
<p>Der Arbeitswirkungsgrad (η<sub>Arbeit</sub>) wurde in zwei der in <a href="#tbl-Wirkungsgrad" class="quarto-xref">Tabelle&nbsp;2</a> dargestellten Studien systematisch untersucht. <span class="citation" data-cites="Gaesser1975">Gaesser &amp; Brooks (<a href="#ref-Gaesser1975" role="doc-biblioref">1975</a>)</span> dokumentiert Werte zwischen 25% und 28%, während <span class="citation" data-cites="Luhtanen1987">Luhtanen et al. (<a href="#ref-Luhtanen1987" role="doc-biblioref">1987</a>)</span> einen Bereich von 21,0% bis 29,7% berichtet. Die Werte bewegen sich damit in einer ähnlichen Größenordnung wie der Delta-Wirkungsgrad. Bezüglich der Einflussfaktoren zeigen sich unterschiedliche Effekte: <span class="citation" data-cites="Gaesser1975">Gaesser &amp; Brooks (<a href="#ref-Gaesser1975" role="doc-biblioref">1975</a>)</span> beobachtet einen Anstieg des η<sub>Arbeit</sub> mit zunehmender Trittfrequenz. <span class="citation" data-cites="Luhtanen1987">Luhtanen et al. (<a href="#ref-Luhtanen1987" role="doc-biblioref">1987</a>)</span> dokumentiert eine Reduktion des η<sub>Arbeit</sub> bei steigender Belastungsintensität.</p>
<p>Der Muskuläre Wirkungsgrad (η<sub>Muskulär</sub>) wurde in <a href="#tbl-Wirkungsgrad" class="quarto-xref">Tabelle&nbsp;2</a> nur von <span class="citation" data-cites="Bell2009">Bell &amp; Ferguson (<a href="#ref-Bell2009" role="doc-biblioref">2009</a>)</span> berichtet und bei normalen Muskeltermperatur werten von durschnittlich 30.2 ± 3.1 bei älteren Menschen und 32.0 ± 3.1 % bei Jungen und bei erhöhten Muskeltemperatur werten von durschnittlich 27.9 ± 4.1 bei älteren 34.0 ± 5.5% bei jüngeren werten angebene. Hier zeigen sich inverse Effekte. Während bei den jungen der Wirkungsgrad snstiegt mi erhöhter muskeltempaeratur sinkt er bei älteren menschen. Diese berichtetn WErte sind die höchsten durchschnittlichen η WErte aller Wirkungsgrad wertein <a href="#tbl-Wirkungsgrad" class="quarto-xref">Tabelle&nbsp;2</a>.</p>
<p>Obwohl ein erhöhter η<sub>Muskulär</sub> aufgrund der Einbeziehung der internen Arbeit für die Aufrechterhaltung der Pedallierbewegung im Vergleich zu den in dieser Studie berichteten η<sub>netto</sub> Wert als plausibel erscheint, erscheinen die dokumentierten Werte im Vergleich zu den anderen in <a href="#tbl-Wirkungsgrad" class="quarto-xref">Tabelle&nbsp;2</a> berichteten η<sub>arbeit</sub> und η<sub>delta</sub> Werten außergewöhnlich hoch. Dies gilt ebenso für den von <span class="citation" data-cites="Bell2009">Bell &amp; Ferguson (<a href="#ref-Bell2009" role="doc-biblioref">2009</a>)</span> dokumentierten η<sub>netto</sub> Wert im Vergleich zu den übrigen Studien. Die Autoren selbst diskutieren diese Auffälligkeit und deuten eine mögliche Überschätzung ihrer Werte im Vergleich zur existierenden Literatur an.</p>
<p><a href="#fig-dePauw" class="quarto-xref">Abbildung&nbsp;1</a></p>
<div id="fig-dePauw" class="caption quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dePauw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/de_Pauw_Leistungsniveau.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Abbildung&nbsp;1: Leistungsniveaus De Pauw et al.&nbsp;(2013)"><img src="images/de_Pauw_Leistungsniveau.png" class="caption img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dePauw-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;1: Leistungsniveaus De Pauw et al.&nbsp;(2013)
</figcaption>
</figure>
</div>
<p><a href="#tbl-Wirkungsgrad" class="quarto-xref">Tabelle&nbsp;2</a></p>
</section>
<section id="limitationen-bei-wirkungsgradberechnungen" class="level2">
<h2 class="anchored" data-anchor-id="limitationen-bei-wirkungsgradberechnungen">Limitationen bei Wirkungsgradberechnungen</h2>
<p>Neben den genannten Studien gibt es noch weitere Untersuchungen, welche den Wirkungsgrad im Radsport ermittelt haben. Bei diesen Untersuchungen ist jedoch zu beachten, dass bei der Berechnung des Wirkungsgrades verschiedene Faktoren berücksichtigt werden müssen, die das Ergebnis beeinflussen können. Die verschiedenen Wirkungsgrade verhalten sich unterschiedlich in Bezug auf Änderungen von P<sub>mech</sub> bei körperlicher Belastung auf dem Radergometer. Zum Beispiel hängt η<sub>brutto</sub> stark von der Belastungsintensität ab und steigt, wenn P<sub>mech</sub> zunimmt. Dies liegt daran, dass der prozentuale Anteil des Ruhestoffwechsels, das heißt der Energie, die für die Aufrechterhaltung grundlegender Körperfunktionen im Ruhezustand erforderlich ist, abnimmt, wenn die Gesamtleistung während sportlicher Aktivitäten ansteigt. η<sub>Arbeit</sub> und η<sub>delta</sub> verhalten sich ähnlich <span class="citation" data-cites="Boning1984">(<a href="#ref-Boning1984" role="doc-biblioref">Böning et al., 1984</a>)</span>. Im Gegensatz dazu ist η<sub>netto</sub> weniger leistungsabhängig <span class="citation" data-cites="Chavarren1999 Coast1985">(<a href="#ref-Chavarren1999" role="doc-biblioref">Chavarren &amp; Calbet, 1999</a>; <a href="#ref-Coast1985" role="doc-biblioref">Coast &amp; Welch, 1985</a>)</span>. Bei der Berechnung von η<sub>netto</sub> werden Veränderungen der Trittrate nicht berücksichtigt, obwohl diese den Nettowirkungsgrad beeinflussen können, selbst wenn P<sub>mech</sub> unverändert bleibt.</p>
<section id="einfluss-der-trittrate-auf-den-wirkungsgrad" class="level3">
<h3 class="anchored" data-anchor-id="einfluss-der-trittrate-auf-den-wirkungsgrad">Einfluss der Trittrate auf den Wirkungsgrad</h3>
<p>Die Veränderung des Wirkungsgrades bei gleichbleibender P<sub>mech</sub> und veränderter Drehzahl ist unter anderem auf interne Leistung/Arbeit, bzw. Blindleistung oder Blindarbeit (P<sub>Int</sub> oder W<sub>Int</sub>) zurückzuführen, die die umgesetzte Energie für die Eigenbewegung der unteren Extremitäten beschreibt. Die interne Leistung ist ein Bestandteil der Gesamtleistung (P<sub>Tot</sub>), die beim Radfahren aufgewendet wird um die Kurbelbewegung zu erzeugen. P<sub>Tot</sub> kann durch die Addition von P<sub>mech</sub> und P<sub>Int</sub> berechnet werden <span class="citation" data-cites="Hansen2007b Sjøgaard2002">(<a href="#ref-Hansen2007b" role="doc-biblioref">Hansen &amp; Sjøgaard, 2007</a>; <a href="#ref-Sjøgaard2002" role="doc-biblioref">Sjøgaard et al., 2002</a>)</span>.</p>
<p>P<sub>Int</sub> berechnet sich aus der rotatorischen kinetischen Energiekomponente (E<sub>kin,rot</sub>) für das Durchführen der Drehbewegungen der Körpersegmente um ihre jeweilige Achse und der translatorischen kinetischen Energiekomponente (E<sub>kin,trans</sub>) zusammen, die die Verschiebung der Segmentschwerpunkte im Raum beschreibt.</p>
<p>Obwohl W<sub>Int</sub> selbst keine externen Vortriebskräfte erzeugt, ist sie für die Aufrechterhaltung der Gesamtbweegung essentiell. Dies steht im Gegensatz zur externen Arbeit (W<sub>Ext</sub>), die direkt mechanische Energie auf das System überträgt, um Vortrieb zu erzeugen. Verschiedene Faktoren beeinflussen die aufzubringende innere Arbeit und führen speziell bei hohen Trittraten zu mehr metabolischen Kosten. Dazu zählen die durch die Hill-Gleichung beschriebene verringerte Muskelkraft bei hoher Kontraktionsgeschwindigkeit, die gleichzeitige Agonisten/Antagonisten-Aktivierung mit verstärktem Abbremsen sowie Reibungs- und Viskositätswiderstände in Gelenken und Strukturen. Besonders das verstärkte Abbremsen bei hohen Drehzahlen durch die Antagonisten erhöht die Blindleistungsanforderungen. Die innere Arbeit sowie deren Berechnung wird in dem Abschnitt “Innere Arbeit” genauer beschrieben.<br> Soll P<sub>Int</sub> bei der Wirkungsgradberechnung berücksichtigt werden, eignet sich der sogenannte muskuläre Wirkungsgrad (η<sub>muskulär</sub>) <span class="citation" data-cites="Boning2017">Böning et al. (<a href="#ref-Boning2017" role="doc-biblioref">2017</a>)</span> (auch “true efficiency” nach <span class="citation" data-cites="Luhtanen1987">Luhtanen et al. (<a href="#ref-Luhtanen1987" role="doc-biblioref">1987</a>)</span>). Dieser beachtet die aufgewandte W<sub>Int</sub> in der Berechnung und ist daher weniger von Änderungen der Trittrate abhängig als η<sub>netto</sub>.</p>
<p><strong>Einfluss der Trittrate auch in <span class="citation" data-cites="Beneke2001">Beneke &amp; Di Prampero (<a href="#ref-Beneke2001" role="doc-biblioref">2001</a>)</span> gut zusammengefasst!!!!!!!!!!!</strong></p>
<p>Ein weiterer Aspekt, der in vielen Untersuchungen des Wirkungsgrades beim Radfahren ungenau bestimmt wurde, ist der physiologische Gesamtenergieumsatz. Häufig wurden nicht die verschiedenen Energiekomponenten (aerobe, anaerobe-laktazide sowie anaerobe-alaktazide Energiekomponente) berechnet, sondern nur der Sauerstoffvolumenstrom<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> gemessen und als Grundlage für die Wirkungsgradberechnung der während der Belastung umgesetzten chemischen Energie verwendet <span class="citation" data-cites="Boning2017">(<a href="#ref-Boning2017" role="doc-biblioref">Böning et al., 2017</a>)</span>. Dadurch wird insbesondere bei hochintensiven Belastungen die Menge des durch anaerobe Glykolyse und energiereiche Phosphate bereitgestellten ATPs vernachlässigt, was zu einer Unterschätzung der gesamten umgesetzten chemischen Energie führt <span class="citation" data-cites="Brooks2004">(<a href="#ref-Brooks2004" role="doc-biblioref">Brooks et al., 2004, S. 354</a>)</span>.</p>
</section>
<section id="wirk-delta" class="level3">
<h3 class="anchored" data-anchor-id="wirk-delta">Wirk Delta</h3>
<p>In der folgenden Arbeit werden alle in Tabell oben beschirebenen Wirkunggrade für die voliegenden Datne berechnet mit der ausnahme von Wirk_Delta. Wirk delta kann aber wie folge beserchnet werden: ### Genaue Berechnugn von Delta Efficiency Die Delta-Effizienz (Δη) quantifiziert den mechanischen Wirkungsgrad während zyklischer Bewegungen am Fahrradergometer und wird aus der linearen Beziehung zwischen Sauerstoffaufnahme (V̇O₂) und externer mechanischer Leistung (P) ermittelt. Die Berechnung basiert auf einer linearen Regressionsanalyse der Form:</p>
<p>V̇O₂ = a + bP</p>
<p>wobei: - a = y-Achsenabschnitt [mlO₂·min⁻¹] - b = Steigung der Regressionsgeraden [mlO₂·W⁻¹·min⁻¹]</p>
<p>Die gemessenen V̇O₂-Werte [mlO₂·min⁻¹] werden unter Berücksichtigung des respiratorischen Quotienten (RQ) in mechanische Leistung transformiert. Das kalorische Äquivalent (kcal·lO₂⁻¹) wird dabei für den jeweiligen RQ-Wert bestimmt und in Joule umgerechnet. Aufgrund der zeitlichen Dimension der V̇O₂-Werte (min⁻¹) erfolgt eine Konversion in Sekunden.</p>
<p>Gegeben: - Steigung b = 11,65 mlO₂·kg⁻¹·W⁻¹ - RQ = 0,97 - Kalorisches Äquivalent bei RQ 0,97 ≈ 4,985 kcal·lO₂⁻¹ - Umrechnung: 1 kcal = 4186,8 J</p>
<p>Berechnung: Δη = 1/(b × (4,985 × 4186,8/1000)/60) Δη = 1/(11,65 × 20,87/60) Δη = 1/4,053 Δη ≈ 0,247 = 24,7%</p>
<p>Die ermittelte Delta-Effizienz von 24,7% repräsentiert einen biomechanisch plausiblen Wert für submaximale zyklische Bewegungen am Fahrradergometer. Die Berechnung berücksichtigt sowohl das spezifische kalorische Äquivalent in Abhängigkeit vom respiratorischen Quotienten als auch die erforderliche temporale Transformation.</p>
<p>Siehe <span class="citation" data-cites="Francescato1995">Francescato et al. (<a href="#ref-Francescato1995" role="doc-biblioref">1995</a>)</span>, <span class="citation" data-cites="Gaesser1975">Gaesser &amp; Brooks (<a href="#ref-Gaesser1975" role="doc-biblioref">1975</a>)</span>, <span class="citation" data-cites="Zoladz2023a">Zoladz et al. (<a href="#ref-Zoladz2023a" role="doc-biblioref">2023</a>)</span>, <span class="citation" data-cites="Ettema2009">Ettema &amp; Lorås (<a href="#ref-Ettema2009" role="doc-biblioref">2009</a>)</span></p>
</section>
</section>
</section>
<section id="quellenverzeichnis" class="level1">
<h1>Quellenverzeichnis</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-Bell2009" class="csl-entry" role="listitem">
Bell, M. P., &amp; Ferguson, R. A. (2009). <span>Interaction between muscle temperature and contraction velocity affects mechanical efficiency during moderate-intensity cycling exercise in young and older women</span>. <em>Journal of Applied Physiology</em>, <em>107</em>(3), 763–769. <a href="https://doi.org/10.1152/japplphysiol.91654.2008">https://doi.org/10.1152/japplphysiol.91654.2008</a>
</div>
<div id="ref-Beneke2001" class="csl-entry" role="listitem">
Beneke, R., &amp; Di Prampero, P. E. (2001). <span>Mechanische und metabolische Belastung beim Radfahren - eine Analyse aus physiologischer und biomechanischer Sicht</span>. <em>Deutsche Zeitschrift f<span>ü</span>r Sportmedizin</em>, <em>52</em>(1), 29–32.
</div>
<div id="ref-Beneke2002" class="csl-entry" role="listitem">
Beneke, R., Pollmann, C., Bleif, I., Leithäuser, R. M., &amp; Hütler, M. (2002). <span>How anaerobic is the Wingate Anaerobic Test for humans ?</span> <em>European Journal of Applied Physiology</em>, <em>87</em>, 388–392. <a href="https://doi.org/10.1007/s00421-002-0622-4">https://doi.org/10.1007/s00421-002-0622-4</a>
</div>
<div id="ref-Boning1984" class="csl-entry" role="listitem">
Böning, D., Gonen, Y., &amp; Maassen, N. (1984). <span>Relationship between work load, pedal frequency, and physical fitness</span>. <em>International Journal of Sports Medicine</em>, <em>5</em>(2), 92–97. <a href="https://doi.org/10.1055/s-2008-1025887">https://doi.org/10.1055/s-2008-1025887</a>
</div>
<div id="ref-Boning2017" class="csl-entry" role="listitem">
Böning, D., Maassen, N., &amp; Steinach, M. (2017). <span>Der Wirkungsgrad von Muskelarbeit</span>. <em>Deutsche Zeitschrift fur Sportmedizin</em>, <em>68</em>(September), 203–214. <a href="https://doi.org/10.5960/dzsm.2017.295">https://doi.org/10.5960/dzsm.2017.295</a>
</div>
<div id="ref-Bouillod2014" class="csl-entry" role="listitem">
Bouillod, A., &amp; Pinot, J. (2014). <span>Gross efficiency is improved in standing position with an increase of the power output</span>. <em>Journal of Science and Cycling</em>, <em>3</em>(July), 2014.
</div>
<div id="ref-Brooks2004" class="csl-entry" role="listitem">
Brooks, G. A., Fahey, T. D., &amp; Baldwin, K. M. (2004). <em><span>Exercise Physiology: Human Bioenergetics and Its Applications</span></em> (4. Edition, S. 928). McGraw-Hill Education Ltd.
</div>
<div id="ref-Carlsson2024" class="csl-entry" role="listitem">
Carlsson, M., Lindblom, O., &amp; Carlsson, T. (2024). <span>Steep uphill cycling using repeated transitions between seated and standing positions results in a lower blood-lactate concentration than continuous use of either seated or standing position</span>. <em>Frontiers in Sports and Active Living</em>, <em>6</em>(September), 1–7. <a href="https://doi.org/10.3389/fspor.2024.1395415">https://doi.org/10.3389/fspor.2024.1395415</a>
</div>
<div id="ref-Chavarren1999" class="csl-entry" role="listitem">
Chavarren, J., &amp; Calbet, J. A. L. (1999). <span>Cycling efficiency and pedalling frequency in road cyclists</span>. <em>European Journal of Applied Physiology and Occupational Physiology</em>, <em>80</em>(6), 555–563. <a href="https://doi.org/10.1007/s004210050634">https://doi.org/10.1007/s004210050634</a>
</div>
<div id="ref-Coast1985" class="csl-entry" role="listitem">
Coast, J. R., &amp; Welch, H. G. (1985). <span>Linear increase in optimal pedal rate with increased power output in cycle ergometry</span>. <em>European Journal of Applied Physiology and Occupational Physiology</em>, <em>53</em>(4), 339–342. <a href="https://doi.org/10.1007/BF00422850">https://doi.org/10.1007/BF00422850</a>
</div>
<div id="ref-Dickinson1929" class="csl-entry" role="listitem">
Dickinson, B. Y. S., &amp; Dickinson, S. (1929). <span>The efficiency of bicycle-pedalling, as affected by speed and load.</span> <em>The Journal of physiology</em>, <em>67</em>(3), 242–255. <a href="https://doi.org/10.1113/jphysiol.1929.sp002565">https://doi.org/10.1113/jphysiol.1929.sp002565</a>
</div>
<div id="ref-Dunst2023a" class="csl-entry" role="listitem">
Dunst, A. K., Hesse, C., Ueberschär, O., &amp; Holmberg, H. C. (2023). <span>A Novel Approach to the Determination of Time- and Fatigue-Dependent Efficiency during Maximal Cycling Sprints</span>. <em>Sports</em>, <em>11</em>(2). <a href="https://doi.org/10.3390/sports11020029">https://doi.org/10.3390/sports11020029</a>
</div>
<div id="ref-Ettema2009" class="csl-entry" role="listitem">
Ettema, G., &amp; Lorås, H. W. (2009). <span>Efficiency in cycling: a review.</span> <em>European journal of applied physiology</em>, <em>106</em>(1), 1–14. <a href="https://doi.org/10.1007/s00421-009-1008-7">https://doi.org/10.1007/s00421-009-1008-7</a>
</div>
<div id="ref-Francescato1995" class="csl-entry" role="listitem">
Francescato, M. P., Giradis, M., &amp; Di Prampero, P. E. (1995). <span>Oxygen cost of internal work during cycling</span>. <em>European Journal of Applied Physiology</em>, <em>72</em>, 51–57.
</div>
<div id="ref-Gaesser1975" class="csl-entry" role="listitem">
Gaesser, G. A., &amp; Brooks, G. A. (1975). <span>Efficiency During Rate Exercise : Effects of Speed and Work</span>. <em>Journal of applied physiology</em>, <em>38</em>(6), 1132–1139.
</div>
<div id="ref-Hansen2007b" class="csl-entry" role="listitem">
Hansen, E. A., &amp; Sjøgaard, G. (2007). <span>Relationship between efficiency and pedal rate in cycling : significance of internal power and muscle fiber type composition</span>. <em>Scandinavian journal of medicine &amp; science in sports</em>, <em>17</em>(4), 408–414. <a href="https://doi.org/10.1111/j.1600-0838.2006.00580.x">https://doi.org/10.1111/j.1600-0838.2006.00580.x</a>
</div>
<div id="ref-Harnish2007" class="csl-entry" role="listitem">
Harnish, C., King, D., &amp; Swensen, T. (2007). <span>Effect of cycling position on oxygen uptake and preferred cadence in trained cyclists during hill climbing at various power outputs</span>. <em>European Journal of Applied Physiology</em>, <em>99</em>(4), 387–391. <a href="https://doi.org/10.1007/s00421-006-0358-7">https://doi.org/10.1007/s00421-006-0358-7</a>
</div>
<div id="ref-Henry1950" class="csl-entry" role="listitem">
Henry, F. M., &amp; DeMoor, J. C. (1950). <span>Metabolic efficiency of exercise in relation to work load at constant speed.</span> <em>Journal of applied physiology</em>, <em>2</em>(9), 481–487. <a href="https://doi.org/10.1152/jappl.1950.2.9.481">https://doi.org/10.1152/jappl.1950.2.9.481</a>
</div>
<div id="ref-Luhtanen1987" class="csl-entry" role="listitem">
Luhtanen, P., Rahkila, P., Rusko, H., &amp; Viitasalo, J. T. (1987). <span>Mechanical work and efficiency in ergometer bicycling at aerobic and anaerobic thresholds</span>. <em>Acta Physiologica Scandinavica</em>, <em>131</em>(3), 331–337. <a href="https://doi.org/10.1111/j.1748-1716.1987.tb08247.x">https://doi.org/10.1111/j.1748-1716.1987.tb08247.x</a>
</div>
<div id="ref-Millet2002" class="csl-entry" role="listitem">
Millet, G., Tronche, C., Fuster, N., &amp; Candau, R. (2002). <span>Level ground and uphill cycling efficiency in seated and standing positions</span>. <em>Medicine and science in sports and exercise</em>, <em>34</em>(October), 1645–1652. <a href="https://doi.org/10.1249/01.MSS.0000031482.14781.D7">https://doi.org/10.1249/01.MSS.0000031482.14781.D7</a>
</div>
<div id="ref-Seabury1977" class="csl-entry" role="listitem">
Seabury, J. J., Adams, W. C., &amp; Ramey, M. R. (1977). <span>Influence of pedalling rate and power output on energy expenditure during bicycle ergometry.</span> <em>Ergonomics</em>, <em>20</em>(5), 491–498. <a href="https://doi.org/10.1080/00140137708931658">https://doi.org/10.1080/00140137708931658</a>
</div>
<div id="ref-Sjøgaard2002" class="csl-entry" role="listitem">
Sjøgaard, G., Hansen, E. A., &amp; Osada, T. (2002). <span>Blood flow and oxygen uptake increase with total power during five different knee-extension contraction rates</span>. <em>Journal of Applied Physiology</em>, <em>93</em>(5), 1676–1684. <a href="https://doi.org/10.1152/japplphysiol.00259.2002">https://doi.org/10.1152/japplphysiol.00259.2002</a>
</div>
<div id="ref-Suzuki1979" class="csl-entry" role="listitem">
Suzuki, Y. (1979). <span>Mechanical efficiency of fast- and slow-twitch muscle fibers in man during cycling</span>. <em>Journal of Applied Physiology Respiratory Environmental and Exercise Physiology</em>, <em>47</em>(2), 263–267. <a href="https://doi.org/10.1152/jappl.1979.47.2.263">https://doi.org/10.1152/jappl.1979.47.2.263</a>
</div>
<div id="ref-Zoladz2023a" class="csl-entry" role="listitem">
Zoladz, J. A., Zapart-Bukowska, J., Grandys, M., Szkutnik, Z., Grassi, B., &amp; Majerczak, J. (2023). <span>Body mass and V’O(2) at rest affect gross efficiency during moderate-intensity cycling in untrained young healthy men: correlations with V’O(2MAX).</span> <em>Journal of physiology and pharmacology</em>, <em>74</em>(5), 507–518. <a href="https://doi.org/10.26402/jpp.2023.5.03">https://doi.org/10.26402/jpp.2023.5.03</a>
</div>
</div>


<!-- -->

</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Fußnoten</h2>

<ol>
<li id="fn1"><p>In der englischsprachigen Literatur wird der Begriff „efficiency“ meist gleichbedeutend für die Wörter “Wirkungsgrad” und “Effizienz” verwendet. Die Effizienz beschreibt allgemein das Verhältnis zwischen dem erreichten Ergebnis und dem dafür benötigten Aufwand oder den dafür eingesetzten Ressourcen, während der Wirkungsgrad spezifisch angibt, wie viel Prozent der aufgewandten Energie tatsächlich in nutzbare Energie umgewandelt wird. So kann im Kontext dieser Arbeit Wirkungsgrad und Effizienz gleichbedeutend sein, solange sich die Effizienz auf das prozentuale Verhältnis von aufgebrachter chemischer Energie gegenüber der tatsächlich erbrachten mechanischen Leistung bezieht.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Der Sauerstoffvolumenstrom oder auch Sauerstofffluss bezeichnet die Menge an Sauerstoff, die innerhalb einer bestimmten Zeitspanne durch ein System oder eine Einheit fließt. In der Sportwissenschaft werden diese Begriffe normalerweise gleichbedeutend mit dem Begriff “Sauerstoffaufnahme” verwendet. In dieser Arbeit beschreibt die Sauerstoffaufnahme das Gesamtvolumen an Sauerstoff, das der Körper innerhalb einem bestimmten Zeitintervall aufgenommen hat.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Kopiert");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Kopiert");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/JJRW96\.github\.io\/Wirkungsgrad-Rad\.github\.io\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Quellcode</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Wirkungsgrad"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">execute:</span><span class="co"> </span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co">  message: false</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">  echo: false</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">  warning: false</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">  error: false</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="an">bibliography:</span><span class="co"> references.bib</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="an">lang:</span><span class="co"> de</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="an">number-sections:</span><span class="co"> false</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="an">editor:</span><span class="co"> </span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="co">  markdown: </span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="co">    wrap: 72</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="an">tbl-cap-location:</span><span class="co"> bottom</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="an">nocite:</span><span class="co"> |</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="co">  @Dickinson1929, @Henry1950, @Gaesser1975, @Seabury1977, @Suzuki1979, @Luhtanen1987, @Francescato1995, @Chavarren1999, @Beneke2002, @Millet2002, @Harnish2007, @Bell2009, @Bouillod2014, @Dunst2023a, @Zoladz2023a, @Carlsson2024</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="in">```{css}</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>#<span class="op">|</span> echo<span class="in">:</span> false</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a>p {</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>  <span class="kw">text-align</span><span class="ch">:</span> <span class="dv">justify</span></span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>caption<span class="op">,</span> <span class="fu">.figure-caption</span> {</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>  <span class="kw">text-align</span><span class="ch">:</span> <span class="dv">left</span><span class="op">;</span></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>figure<span class="fu">.quarto-float-tbl</span> figcaption {</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>  <span class="kw">text-align</span><span class="ch">:</span> <span class="dv">left</span> <span class="at">!important</span><span class="op">;</span></span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>```</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a># Wirkungsgrad</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>library<span class="in">(</span>dplyr<span class="in">)</span></span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>library<span class="in">(</span>tidyr<span class="in">)</span></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>library<span class="in">(</span>readxl<span class="in">)</span></span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>library<span class="in">(</span>ggplot2<span class="in">)</span></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>library<span class="in">(</span>DT<span class="in">)</span></span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>library<span class="in">(</span>extrafont<span class="in">)</span></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>```</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a><span class="op">**</span>Geile Einleitung in <span class="im">@Beneke2001</span>**</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>::: columns</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a>::: {<span class="fu">.column</span> width="52%"}</span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>Der Wirkungsgrad<span class="ex">[</span><span class="op">^</span><span class="ss">1</span><span class="ex">]</span> definiert das Verhältnis von umgesetzter chemischer Energie zur erzeugten mechanischen Energie. Er wird üblicherweise als Dezimalzahl oder Prozentwert ausgedrückt.&lt;br<span class="op">&gt;</span> Es existieren mehrere Möglichkeiten den Wirkungsgrad zu berechnen<span class="op">,</span> darunter den Bruttowirkungsgrad <span class="in">(</span>η<span class="op">~</span>brutto<span class="op">~</span><span class="in">)</span><span class="op">,</span> den Nettowirkungsgrad <span class="in">(</span>η<span class="op">~</span>netto<span class="op">~</span><span class="in">)</span><span class="op">,</span> den Arbeitswirkungsgrad <span class="in">(</span>η<span class="op">~</span>Arbeit<span class="op">~</span><span class="in">)</span> sowie den Deltawirkungsgrad <span class="in">(</span>η<span class="op">~</span>delta<span class="op">~</span><span class="in">)</span> <span class="in">(</span>siehe @tbl-Wirkungsgrad_Berechnungen<span class="in">)</span>. Gewisse Bestimmungsverfahren ermöglichen zwar eine einfache Anwendung<span class="op">,</span> können jedoch mehrere Ungenauigkeiten bzw. Einflussfaktoren beinhalten. Andere hingegen erfordern komplexere Berechnungen und eine größere Anzahl an Messdaten<span class="op">,</span> liefern dafür aber präzisere Daten. In der nachfolgenden Tabelle sind verschiedene Möglichkeiten zur Wirkungsgradberechnung aufgeführt <span class="ex">[</span><span class="ss">@Boning2017</span>; <span class="im">@Luhtanen1987</span><span class="op">;</span> <span class="im">@Gaesser1975</span>]:</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>:::</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>::: {<span class="fu">.column</span> width="2%"}</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a><span class="in">:::</span></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="in">:::</span> {<span class="fu">.column</span> width="46%"}</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a><span class="op">|</span> Wirkungsgrade <span class="op">|</span>               Berechnung                <span class="op">|</span></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="op">|</span>---------------<span class="op">|</span><span class="in">:---------------------------------------:</span><span class="op">|</span></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="op">|</span> η<span class="op">~</span>Brutto<span class="op">~</span>     <span class="op">|</span>            P<span class="op">~</span>mech<span class="op">~</span> / E<span class="op">~</span>Aerob<span class="op">~</span>             <span class="op">|</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="op">|</span> η<span class="op">~</span>Netto<span class="op">~</span>      <span class="op">|</span>      P<span class="op">~</span>mech<span class="op">~</span> / <span class="in">(</span>E<span class="op">~</span>Aerob<span class="op">~</span>&nbsp;-&nbsp;E<span class="op">~</span>Ruhe<span class="op">~</span><span class="in">)</span>       <span class="op">|</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="op">|</span> η<span class="op">~</span>Total<span class="op">~</span>      <span class="op">|</span>      P<span class="op">~</span>mech<span class="op">~</span>  / <span class="in">(</span>E<span class="op">~</span>Tot<span class="op">~</span>&nbsp;-&nbsp;E<span class="op">~</span>Ruhe<span class="op">~</span><span class="in">)</span> <span class="op">|</span></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="op">|</span> η<span class="op">~</span>muskulär<span class="op">~</span>   <span class="op">|</span> <span class="in">(</span>P<span class="op">~</span>mech<span class="op">~</span> <span class="op">+</span> P<span class="op">~</span>Int<span class="op">~</span><span class="in">)</span> / <span class="in">(</span>E<span class="op">~</span>Tot<span class="op">~</span>&nbsp;-&nbsp;E<span class="op">~</span>Ruhe<span class="op">~</span><span class="in">)</span> <span class="op">|</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="op">|</span> η<span class="op">~</span>Arbeit<span class="op">~</span>     <span class="op">|</span>  P<span class="op">~</span>mech<span class="op">~</span> / <span class="in">(</span>E<span class="op">~</span>Tot<span class="op">~</span> -&nbsp;E<span class="op">~</span>Ruhe<span class="op">~</span> -&nbsp;E<span class="op">~</span>Leerbewegung<span class="op">~</span><span class="in">)</span>   <span class="op">|</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="op">|</span> η<span class="op">~</span>delta<span class="op">~</span>      <span class="op">|</span>           ΔP<span class="op">~</span>mech<span class="op">~</span> / ΔE<span class="op">~</span>Tot<span class="op">~</span>            <span class="op">|</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="in">:</span> Modifizierte Berechnungswege der Wirkungsgrade nach Gaesser und Brooks <span class="in">(</span>1975<span class="in">)</span><span class="op">,</span> Luhtanen et al. <span class="in">(</span>1987<span class="in">)</span> und Böning et al. <span class="in">(</span>2017<span class="in">)</span><span class="op">,</span> ergänzt um den Gesamtwirkungsgrad <span class="in">(</span>η<span class="op">~</span>Total<span class="op">~</span><span class="in">)</span>. {<span class="pp">#tbl-Wirkungsgrad_Berechnungen</span> tbl-colwidths="\[30<span class="op">,</span>70\]" <span class="fu">.hover</span> }</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="in">:::</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a><span class="in">:::</span></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="ex">[</span><span class="op">^</span><span class="ss">1</span><span class="ex">]</span><span class="in">:</span> In der englischsprachigen Literatur wird der Begriff „efficiency“ meist gleichbedeutend für die Wörter "Wirkungsgrad" und "Effizienz" verwendet. Die Effizienz beschreibt allgemein das Verhältnis zwischen dem erreichten Ergebnis und dem dafür benötigten Aufwand oder den dafür eingesetzten Ressourcen<span class="op">,</span> während der Wirkungsgrad spezifisch angibt<span class="op">,</span> wie viel Prozent der aufgewandten Energie tatsächlich in nutzbare Energie umgewandelt wird. So kann im Kontext dieser Arbeit Wirkungsgrad und Effizienz gleichbedeutend sein<span class="op">,</span> solange sich die Effizienz auf das prozentuale Verhältnis von aufgebrachter chemischer Energie gegenüber der tatsächlich erbrachten mechanischen Leistung bezieht.</span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a><span class="op">**</span>Temperaturregulation bei körperlicher Belastung bzw. wo geht die Wärmeenergie hin noch mit einbeziehen und beschrieben!!!!!!!!!!!!!! --<span class="op">&gt;</span> Aschoff<span class="op">,</span> Stegemann<span class="op">,</span> deMaares S<span class="fu">.552</span><span class="op">,</span> Astrand S. 396<span class="op">**</span></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a><span class="op">**</span>Statt über indirekte Kaliometrie über die Wärmeabgabe den Wirkungsgrad gegenrechnen oder direkt Berechnen?????<span class="op">**</span></span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="op">**</span>NOCH ZUSÄTzLICH DIE BERECHNUNG VON WIRK_TOTAL MIT BESCHREBEN --<span class="op">&gt;</span> VERGLICH ZWISCHEN WIRK MUSKULÄR UND TOTAL --<span class="op">&gt;</span> EINFLUSS VON PINT<span class="op">**</span></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a><span class="pp">#Auch</span> in <span class="im">@Gaesser1975</span> beschrieben***&lt;br&gt; ***-\&gt; Studie von [@Ettema2009] noch mit einbeziehen&lt;br&gt; </span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>#![Wirkungsgrade nach <span class="fu">(</span><span class="dv">Luhtanen</span>, <span class="dv">1987</span><span class="fu">)</span>]<span class="fu">(</span><span class="dv">images</span>/<span class="dv">Wirkungsgrad_Luhtanen1978</span>.<span class="dv">png</span><span class="fu">)</span>{<span class="pp">#fig-LUH</span> <span class="fu">.caption</span> width="289"} </span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>#!<span class="ex">[</span><span class="ss">Wirkungsgrade nach (Chavarren</span><span class="op">,</span> 1999)]<span class="in">(</span>images/Wirkungsgrad_Chavarren<span class="fu">.png</span><span class="in">)</span>{<span class="pp">#fig-CHAV</span> <span class="fu">.caption</span> width="289"} </span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>#!<span class="ex">[</span><span class="ss">Wirkungsgrade nach (Gaesser</span><span class="op">,</span> 1975)]<span class="in">(</span>images/Wirkungsgrad_Gaesser_1<span class="fu">.png</span><span class="in">)</span>{<span class="pp">#fig-GAE1</span> <span class="fu">.caption</span> width="289"} </span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a>#!<span class="ex">[</span><span class="ss">Wirkungsgrade nach (Gaesser</span><span class="op">,</span> 1975)]<span class="in">(</span>images/Wirkungsgrad_Gaesser_2<span class="fu">.png</span><span class="in">)</span>{<span class="pp">#fig-GAE2</span> <span class="fu">.caption</span> width="289"}</span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>## IN TABELLEN VERLINKEN!!!!</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a><span class="pp">#Hopker2010</span> für den Vergleich von Frauen und Männer beim Radfahren</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a><span class="pp">#EINTELUNG</span> IN DER TABELLE der PROBANDEN NACH der TABELLE von <span class="im">@Jeukendrup2000</span> vornehmen. Oder nach @dePauw2013 </span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a># -&gt; Oder Beides wie in @Ronnestadt2022 <span class="st">"All cyclists were categorized as performance level 4 to 5 (17), equal to being elite (18)."</span></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>```</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>#| label: tbl-Wirkungsgrad</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>#| tbl-cap-location: top</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a>#| tbl-cap:  <span class="st">"Tabellarische Übersicht unterschiedlich berechneter Wirkungsgrade beim Fahrradfahren unter verschiedenen Bedingungen"</span></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a>library<span class="fu">(</span><span class="dv">flextable</span><span class="fu">)</span></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a>library<span class="fu">(</span><span class="dv">dplyr</span><span class="fu">)</span></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a>library<span class="fu">(</span><span class="dv">officer</span><span class="fu">)</span></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a>ft_Wirkungsgrad &lt;- readRDS<span class="fu">(</span><span class="st">"rds/ft_Wirkungsgrad.rds"</span><span class="fu">)</span></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a># Anzeigen der Tabelle</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>ft_Wirkungsgrad</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>```</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>## Werte aus der Literatur</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a>Die aus der Fachliteratur ausgewählten und in der @tbl-Wirkungsgrad dargestellten Wirkungsgrade zeigen eine erhebliche Variabilität, wobei systematische Unterschiede zwischen den verschiedenen Berechnungsmethoden erkennbar sind. </span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a>Der Bruttowirkungsgrad <span class="fu">(</span><span class="dv">η</span>~<span class="dv">brutto</span>~<span class="fu">)</span> weist konsistent die niedrigsten Werte aller berechneten Wirkungsgrade auf. Die Spannweite der gemessenen Werte reicht von unter 10% [@Gaesser1975<span class="op">;</span><span class="im">@Dunst2023a</span>], die charakteristischerweise bei extrem hoher Drehzahl, sehr geringer Last oder einer Kombination beider Faktoren auftreten, bis zu Maximalwerten von 23,6% [@Seabury1977], die bei hohen Lasten und moderaten Drehzahlen dokumentiert wurden. Mit typischen Werten zwischen 19% und 22% stellt sich ein charakteristischer Bereich dar, der in vielen Studien bestätigt wird. In der Regel steigt η~brutto~ mit steigender Belastungsintensität, da hier der Anteil des Ruheenergiestoffwechsels kleiner wird und sinkt mit hohen Trittraten.</span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a>Der Nettowirkungsgrad <span class="fu">(</span><span class="dv">η</span>~<span class="dv">netto</span>~<span class="fu">)</span> eliminiert den Einfluss des Ruheenergieumsatzes und zeigt dadurch systematisch höhere Werte als der Bruttowirkungsgrad. Die dokumentierten Werte in den Studien bewegen sich überwiegend zwischen 19% und 24%. Die Abhängigkeit von der Belastungsintensität zeigt in der Literatur unterschiedliche Effekte: Während @Luhtanen1987 einen Abfall des η~netto~ von 21,8% auf 17,5% und @Henry1950 von 21,2% auf 19,3% mit steigender Intensität dokumentiert, berichten sowohl @Gaesser1975 als auch @Harnish2007 einen Anstieg des η~netto~ mit zunehmender Belastung. Diese gegensätzlichen Befunde könnten auf unterschiedliche Testprotokolle und Probandencharakteristika zurückzuführen sein. Ein konsistenterer Effekt zeigt sich bei der Trittrate: Hohe Drehzahlen führen hier zu einem deutlichen Abfall des η~netto~ [@Gaesser1975<span class="op">;</span> <span class="im">@Dickinson1929</span>].</span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a>Der Delta-Wirkungsgrad <span class="fu">(</span><span class="dv">η</span>~<span class="dv">delta</span>~<span class="fu">)</span> weist mit Ausnahme von η~Muskulär~ die höchsten Werte der verschiedenen Berechnungsmethoden auf. Die dokumentierten Werte bewegen sich typischerweise zwischen 23% und 28%. Die Spannweite reicht von Minimalwerten um 20% [@Suzuki1979] bis zu Maximalwerten von über 32% [@Francescato1995]. Im Gegensatz zu η~brutto~ und η~netto~ zeigt η~delta~ keinen Abfall mit steigender Trittrate, da durch die Berechnungsmethode der Energieumsatz für das Pedalieren ohne Last, welcher mit steigender Drehzahl zunimmt, nicht einbezogen wird. So berichten @Francescato1995, @Chavarren1999 und @Gaesser1975 sogar einen Anstieg des η~delta~ mit steigender Drehzahl. Differenzierte Ergebnisse zeigen sich bei @Suzuki1979: Bei Probanden mit überwiegend schnellen Muskelfasern <span class="fu">(</span><span class="dv">FT</span><span class="fu">)</span> steigt η~delta~ bei hohen Drehzahlen an, während bei Probanden mit überwiegend langsamen Muskelfasern <span class="fu">(</span><span class="dv">ST</span><span class="fu">)</span> η~delta~ bei hohen Drehzahlen abnimmt.</span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>Der Arbeitswirkungsgrad <span class="fu">(</span><span class="dv">η</span>~<span class="dv">Arbeit</span>~<span class="fu">)</span> wurde in zwei der in @tbl-Wirkungsgrad dargestellten Studien systematisch untersucht. @Gaesser1975 dokumentiert Werte zwischen 25% und 28%, während @Luhtanen1987 einen Bereich von 21,0% bis 29,7% berichtet. Die Werte bewegen sich damit in einer ähnlichen Größenordnung wie der Delta-Wirkungsgrad. Bezüglich der Einflussfaktoren zeigen sich unterschiedliche Effekte: @Gaesser1975 beobachtet einen Anstieg des η~Arbeit~ mit zunehmender Trittfrequenz. @Luhtanen1987 dokumentiert eine Reduktion des η~Arbeit~ bei steigender Belastungsintensität.</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>Der Muskuläre Wirkungsgrad <span class="fu">(</span><span class="dv">η</span>~<span class="dv">Muskulär</span>~<span class="fu">)</span> wurde in @tbl-Wirkungsgrad nur von @Bell2009 berichtet und bei normalen Muskeltermperatur werten von durschnittlich 30.2 ± 3.1 bei älteren Menschen und 32.0 ± 3.1 % bei Jungen und bei erhöhten Muskeltemperatur werten von durschnittlich 27.9 ± 4.1 bei älteren 34.0 ± 5.5% bei jüngeren werten angebene. Hier zeigen sich inverse Effekte. Während bei den jungen  der Wirkungsgrad snstiegt mi erhöhter muskeltempaeratur sinkt er bei älteren menschen. Diese berichtetn WErte sind die höchsten durchschnittlichen η WErte aller Wirkungsgrad wertein @tbl-Wirkungsgrad. </span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>Obwohl ein erhöhter η~Muskulär~ aufgrund der Einbeziehung der internen Arbeit für die Aufrechterhaltung der Pedallierbewegung im Vergleich zu den in dieser Studie berichteten η~netto~ Wert als plausibel erscheint, erscheinen die dokumentierten Werte im Vergleich zu den anderen in @tbl-Wirkungsgrad berichteten η~arbeit~ und η~delta~ Werten außergewöhnlich hoch. Dies gilt ebenso für den von @Bell2009 dokumentierten η~netto~ Wert im Vergleich zu den übrigen Studien. Die Autoren selbst diskutieren diese Auffälligkeit und deuten eine mögliche Überschätzung ihrer Werte im Vergleich zur existierenden Literatur an.</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a>@fig-dePauw</span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a>![Leistungsniveaus De Pauw et al. <span class="fu">(</span><span class="dv">2013</span><span class="fu">)</span>]<span class="fu">(</span><span class="dv">images</span>/<span class="dv">de_Pauw_Leistungsniveau</span>.<span class="dv">png</span><span class="fu">)</span>{<span class="pp">#fig-dePauw</span> <span class="fu">.caption</span>} </span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a><span class="im">@tbl-Wirkungsgrad</span></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a>## Limitationen bei Wirkungsgradberechnungen</span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a>Neben den genannten Studien gibt es noch weitere Untersuchungen, welche den Wirkungsgrad im Radsport ermittelt haben. Bei diesen Untersuchungen ist jedoch zu beachten, dass bei der Berechnung des Wirkungsgrades verschiedene Faktoren berücksichtigt werden müssen, die das Ergebnis beeinflussen können. Die verschiedenen Wirkungsgrade verhalten sich unterschiedlich in Bezug auf Änderungen von P~mech~ bei körperlicher Belastung auf dem Radergometer. Zum Beispiel hängt η~brutto~ stark von der Belastungsintensität ab und steigt, wenn P~mech~ zunimmt. Dies liegt daran, dass der prozentuale Anteil des Ruhestoffwechsels, das heißt der Energie, die für die Aufrechterhaltung grundlegender Körperfunktionen im Ruhezustand erforderlich ist, abnimmt, wenn die Gesamtleistung während sportlicher Aktivitäten ansteigt. η~Arbeit~ und η~delta~ verhalten sich ähnlich [@Boning1984]. Im Gegensatz dazu ist η~netto~ weniger leistungsabhängig [@Chavarren1999<span class="op">;</span> <span class="im">@Coast1985</span>]. Bei der Berechnung von η~netto~ werden Veränderungen der Trittrate nicht berücksichtigt, obwohl diese den Nettowirkungsgrad beeinflussen können, selbst wenn P~mech~ unverändert bleibt.</span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>#Studien präzisieren welche Defizite aufweißen</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a># In @Gaesser1975 gut beschrieben***</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>```</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a>### Einfluss der Trittrate auf den Wirkungsgrad</span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a>Die Veränderung des Wirkungsgrades bei gleichbleibender P~mech~ und veränderter Drehzahl ist unter anderem auf interne Leistung/Arbeit, bzw. Blindleistung oder Blindarbeit <span class="fu">(</span><span class="dv">P</span>~<span class="dv">Int</span>~ <span class="dv">oder W</span>~<span class="dv">Int</span>~<span class="fu">)</span> zurückzuführen, die die umgesetzte Energie für die Eigenbewegung der unteren Extremitäten beschreibt. Die interne Leistung ist ein Bestandteil der Gesamtleistung <span class="fu">(</span><span class="dv">P</span>~<span class="dv">Tot</span>~<span class="fu">)</span>, die beim Radfahren aufgewendet wird um die Kurbelbewegung zu erzeugen. P~Tot~ kann durch die Addition von P~mech~ und P~Int~ berechnet werden [@Hansen2007b<span class="op">;</span> <span class="im">@Sj</span>øgaard2002].</span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>#abnehmende torque Efficiency bei höherer rittrate --&gt; Oder anders herum?</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a>```</span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>P~Int~ berechnet sich aus der rotatorischen kinetischen Energiekomponente <span class="fu">(</span><span class="dv">E</span>~<span class="dv">kin</span>,<span class="dv">rot</span>~<span class="fu">)</span> für das Durchführen der Drehbewegungen der Körpersegmente um ihre jeweilige Achse und der translatorischen kinetischen Energiekomponente <span class="fu">(</span><span class="dv">E</span>~<span class="dv">kin</span>,<span class="dv">trans</span>~<span class="fu">)</span> zusammen, die die Verschiebung der Segmentschwerpunkte im Raum beschreibt.</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>#Zudem sollte die potenzielle Energie und deren Nutzung für die Hubarbeit des gesamten Körperschwerpunktes berücksichtigt werden.</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>```</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>Obwohl W~Int~ selbst keine externen Vortriebskräfte erzeugt, ist sie für die Aufrechterhaltung der Gesamtbweegung essentiell. Dies steht im Gegensatz zur externen Arbeit <span class="fu">(</span><span class="dv">W</span>~<span class="dv">Ext</span>~<span class="fu">)</span>, die direkt mechanische Energie auf das System überträgt, um Vortrieb zu erzeugen. Verschiedene Faktoren beeinflussen die aufzubringende innere Arbeit und führen speziell bei hohen Trittraten zu mehr metabolischen Kosten. Dazu zählen die durch die Hill-Gleichung beschriebene verringerte Muskelkraft bei hoher Kontraktionsgeschwindigkeit, die gleichzeitige Agonisten/Antagonisten-Aktivierung mit verstärktem Abbremsen sowie Reibungs- und Viskositätswiderstände in Gelenken und Strukturen. Besonders das verstärkte Abbremsen bei hohen Drehzahlen durch die Antagonisten erhöht die Blindleistungsanforderungen. Die innere Arbeit sowie deren Berechnung wird in dem Abschnitt <span class="st">"Innere Arbeit"</span> genauer beschrieben.&lt;br&gt; Soll P~Int~ bei der Wirkungsgradberechnung berücksichtigt werden, eignet sich der sogenannte muskuläre Wirkungsgrad <span class="fu">(</span><span class="dv">η</span>~<span class="dv">muskulär</span>~<span class="fu">)</span> @Boning2017 <span class="fu">(</span><span class="dv">auch </span><span class="st">"true efficiency"</span> <span class="dv">nach </span>@<span class="dv">Luhtanen1987</span><span class="fu">)</span>. Dieser beachtet die aufgewandte W~Int~ in der Berechnung und ist daher weniger von Änderungen der Trittrate abhängig als η~netto~.</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>**Einfluss der Trittrate auch in @Beneke2001 gut zusammengefasst!!!!!!!!!!!**</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>## Link Sections</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a>#The answer by Franky works, but Quarto imposes for blogs a special file organisation which requires to be carefull.</span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a>#Each post is a new folder <span class="kw">and</span> the default file name is index.qmd, so you have something like for your source:</span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a>#post1/</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a>    #index.qmd</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a>    #... possibly other files</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>#post2/</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>    #index.qmd</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>#... <span class="kw">and</span> so forth ...</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>#you can rename index.qmd file, but usually you just let it as-is.</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>#In post2/index.qmd you can refer to post1 using the Julian<span class="st">'s trick like this:</span></span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>#[in my previous post]<span class="fu">(</span>../<span class="dv">post1</span>/<span class="dv">index</span>.<span class="dv">qmd</span>]  </span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a>#<span class="dv">you can also refer to parts of other posts using the standard quarto cross-reference syntax</span><span class="ch">:</span></span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>#[<span class="dv">in the figure from my previous post</span>]<span class="fu">(</span>../<span class="dv">post1</span>/<span class="dv">index</span>.<span class="dv">qmd</span>#<span class="dv">fig-elephant</span>]  </span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a>#<span class="dv">works also for sections</span>, <span class="dv">equations</span>, <span class="dv">etc</span>.</span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a>```</span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a><span class="dv">Ein weiterer Aspekt</span>, <span class="dv">der in vielen Untersuchungen des Wirkungsgrades beim Radfahren ungenau bestimmt wurde</span>, <span class="dv">ist der physiologische Gesamtenergieumsatz</span>. <span class="dv">Häufig wurden nicht die verschiedenen Energiekomponenten </span><span class="fu">(</span><span class="dv">aerobe</span>, <span class="dv">anaerobe-laktazide sowie anaerobe-alaktazide Energiekomponente</span><span class="fu">)</span> <span class="dv">berechnet</span>, <span class="dv">sondern nur der Sauerstoffvolumenstrom</span>[^<span class="dv">2</span>] <span class="dv">gemessen und als Grundlage für die Wirkungsgradberechnung der während der Belastung umgesetzten chemischen Energie verwendet </span>[@<span class="dv">Boning2017</span>]. <span class="dv">Dadurch wird insbesondere bei hochintensiven Belastungen die Menge des durch anaerobe Glykolyse und energiereiche Phosphate bereitgestellten ATPs vernachlässigt</span>, <span class="dv">was zu einer Unterschätzung der gesamten umgesetzten chemischen Energie führt </span>[@<span class="dv">Brooks2004</span>, <span class="dv">354</span>].</span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>[^<span class="dv">2</span>]<span class="ch">:</span> <span class="dv">Der Sauerstoffvolumenstrom oder auch Sauerstofffluss bezeichnet die Menge an Sauerstoff</span>, <span class="dv">die innerhalb einer bestimmten Zeitspanne durch ein System oder eine Einheit fließt</span>. <span class="dv">In der Sportwissenschaft werden diese Begriffe normalerweise gleichbedeutend mit dem Begriff </span><span class="st">"Sauerstoffaufnahme"</span> <span class="dv">verwendet</span>. <span class="dv">In dieser Arbeit beschreibt die Sauerstoffaufnahme das Gesamtvolumen an Sauerstoff</span>, <span class="dv">das der Körper innerhalb einem bestimmten Zeitintervall aufgenommen hat</span>.</span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a># <span class="dv">Überleitung Energieberechnung</span></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a>```</span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a>### <span class="dv">Wirk Delta</span></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a><span class="dv">In der folgenden Arbeit werden alle in Tabell oben beschirebenen Wirkunggrade für die voliegenden Datne berechnet mit der ausnahme von Wirk_Delta</span>. <span class="dv">Wirk delta kann aber wie folge beserchnet werden</span><span class="ch">:</span> </span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a>### <span class="dv">Genaue Berechnugn von Delta Efficiency </span></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a><span class="dv">Die Delta-Effizienz </span><span class="fu">(</span><span class="dv">Δη</span><span class="fu">)</span> <span class="dv">quantifiziert den mechanischen Wirkungsgrad während zyklischer Bewegungen am Fahrradergometer und wird aus der linearen Beziehung zwischen Sauerstoffaufnahme </span><span class="fu">(</span><span class="dv">V</span>̇<span class="dv">O₂</span><span class="fu">)</span> <span class="dv">und externer mechanischer Leistung </span><span class="fu">(</span><span class="dv">P</span><span class="fu">)</span> <span class="dv">ermittelt</span>. <span class="dv">Die Berechnung basiert auf einer linearen Regressionsanalyse der Form</span><span class="ch">:</span></span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a><span class="dv">V</span>̇<span class="dv">O₂ </span><span class="op">=</span> <span class="dv">a </span>+ <span class="dv">bP</span></span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a><span class="dv">wobei</span><span class="ch">:</span></span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a><span class="dv">- a </span><span class="op">=</span> <span class="dv">y-Achsenabschnitt </span>[<span class="dv">mlO₂</span>·<span class="dv">min</span>⁻<span class="dv">¹</span>]</span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a><span class="dv">- b </span><span class="op">=</span> <span class="dv">Steigung der Regressionsgeraden </span>[<span class="dv">mlO₂</span>·<span class="dv">W</span>⁻<span class="dv">¹</span>·<span class="dv">min</span>⁻<span class="dv">¹</span>]</span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a><span class="dv">Die gemessenen V</span>̇<span class="dv">O₂-Werte </span>[<span class="dv">mlO₂</span>·<span class="dv">min</span>⁻<span class="dv">¹</span>] <span class="dv">werden unter Berücksichtigung des respiratorischen Quotienten </span><span class="fu">(</span><span class="dv">RQ</span><span class="fu">)</span> <span class="dv">in mechanische Leistung transformiert</span>. <span class="dv">Das kalorische Äquivalent </span><span class="fu">(</span><span class="dv">kcal</span>·<span class="dv">lO₂</span>⁻<span class="dv">¹</span><span class="fu">)</span> <span class="dv">wird dabei für den jeweiligen RQ-Wert bestimmt und in Joule umgerechnet</span>. <span class="dv">Aufgrund der zeitlichen Dimension der V</span>̇<span class="dv">O₂-Werte </span><span class="fu">(</span><span class="dv">min</span>⁻<span class="dv">¹</span><span class="fu">)</span> <span class="dv">erfolgt eine Konversion in Sekunden</span>.</span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a><span class="dv">Gegeben</span><span class="ch">:</span></span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a><span class="dv">- Steigung b </span><span class="op">=</span> <span class="dv">11</span>,<span class="dv">65</span> <span class="dv">mlO₂</span>·<span class="dv">kg</span>⁻<span class="dv">¹</span>·<span class="dv">W</span>⁻<span class="dv">¹</span></span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a><span class="dv">- RQ </span><span class="op">=</span> <span class="dv">0</span>,<span class="dv">97</span></span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a><span class="dv">- Kalorisches Äquivalent bei RQ 0</span>,<span class="dv">97</span> ≈ <span class="dv">4</span>,<span class="dv">985</span> <span class="dv">kcal</span>·<span class="dv">lO₂</span>⁻<span class="dv">¹</span></span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a><span class="dv">- Umrechnung</span><span class="ch">:</span> <span class="dv">1</span> <span class="dv">kcal </span><span class="op">=</span> <span class="dv">4186</span>,<span class="dv">8</span> <span class="dv">J</span></span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a><span class="dv">Berechnung</span><span class="ch">:</span></span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a><span class="dv">Δη </span><span class="op">=</span> <span class="dv">1</span>/<span class="fu">(</span><span class="dv">b </span>× <span class="fu">(</span><span class="dv">4</span>,<span class="dv">985</span> × <span class="dv">4186</span>,<span class="dv">8</span>/<span class="dv">1000</span><span class="fu">)</span>/<span class="dv">60</span><span class="fu">)</span></span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a><span class="dv">Δη </span><span class="op">=</span> <span class="dv">1</span>/<span class="fu">(</span><span class="dv">11</span>,<span class="dv">65</span> × <span class="dv">20</span>,<span class="dv">87</span>/<span class="dv">60</span><span class="fu">)</span></span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a><span class="dv">Δη </span><span class="op">=</span> <span class="dv">1</span>/<span class="dv">4</span>,<span class="dv">053</span></span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a><span class="dv">Δη </span>≈ <span class="dv">0</span>,<span class="dv">247</span> <span class="op">=</span> <span class="dv">24</span>,<span class="dv">7</span><span class="dt">%</span></span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a><span class="dv">Die ermittelte Delta-Effizienz von 24</span>,<span class="dv">7</span><span class="dt">%</span> <span class="dv">repräsentiert einen biomechanisch plausiblen Wert für submaximale zyklische Bewegungen am Fahrradergometer</span>. <span class="dv">Die Berechnung berücksichtigt sowohl das spezifische kalorische Äquivalent in Abhängigkeit vom respiratorischen Quotienten als auch die erforderliche temporale Transformation</span>.</span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a><span class="dv">Siehe </span>@<span class="dv">Francescato1995</span>, @<span class="dv">Gaesser1975</span>, @<span class="dv">Zoladz2023a</span>, @<span class="dv">Ettema2009</span></span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a># <span class="dv">Quellenverzeichnis</span></span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a><span class="ch">:::</span> <span class="er">{</span><span class="pp">#refs</span>}</span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a><span class="in">:::</span></span>
</code><button title="In die Zwischenablage kopieren" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Johannes Will, 2024</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p><a href="https://quarto.org/">Quarto</a></p>
</div>
  </div>
</footer>
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>