on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: "Setup R dependencies for Quarto's knitr engine"
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages:
            cran::shinylive@0.1.1
            any::knitr
            any::rmarkdown
            any::downlit
            any::xml2
            any::shiny
            any::plotly
            any::minpack.lm
            any::DT
            any::patchwork
            any::zoo
            any::ggplot2
            any::dplyr
            any::tidyr
            any::htmltools
            any::htmlwidgets
            any::RColorBrewer
            any::purrr
            any::readxl

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}